/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	archiverv1alpha1 "kubedb.dev/apimachinery/apis/archiver/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdArchiversGetter has a method to return a EtcdArchiverInterface.
// A group's client should implement this interface.
type EtcdArchiversGetter interface {
	EtcdArchivers(namespace string) EtcdArchiverInterface
}

// EtcdArchiverInterface has methods to work with EtcdArchiver resources.
type EtcdArchiverInterface interface {
	Create(ctx context.Context, etcdArchiver *archiverv1alpha1.EtcdArchiver, opts v1.CreateOptions) (*archiverv1alpha1.EtcdArchiver, error)
	Update(ctx context.Context, etcdArchiver *archiverv1alpha1.EtcdArchiver, opts v1.UpdateOptions) (*archiverv1alpha1.EtcdArchiver, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcdArchiver *archiverv1alpha1.EtcdArchiver, opts v1.UpdateOptions) (*archiverv1alpha1.EtcdArchiver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*archiverv1alpha1.EtcdArchiver, error)
	List(ctx context.Context, opts v1.ListOptions) (*archiverv1alpha1.EtcdArchiverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *archiverv1alpha1.EtcdArchiver, err error)
	EtcdArchiverExpansion
}

// etcdArchivers implements EtcdArchiverInterface
type etcdArchivers struct {
	*gentype.ClientWithList[*archiverv1alpha1.EtcdArchiver, *archiverv1alpha1.EtcdArchiverList]
}

// newEtcdArchivers returns a EtcdArchivers
func newEtcdArchivers(c *ArchiverV1alpha1Client, namespace string) *etcdArchivers {
	return &etcdArchivers{
		gentype.NewClientWithList[*archiverv1alpha1.EtcdArchiver, *archiverv1alpha1.EtcdArchiverList](
			"etcdarchivers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *archiverv1alpha1.EtcdArchiver { return &archiverv1alpha1.EtcdArchiver{} },
			func() *archiverv1alpha1.EtcdArchiverList { return &archiverv1alpha1.EtcdArchiverList{} },
		),
	}
}
