/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubedb.dev/apimachinery/apis/courier/v1alpha1"
)

// FakeMySQLMigrations implements MySQLMigrationInterface
type FakeMySQLMigrations struct {
	Fake *FakeCourierV1alpha1
	ns   string
}

var mysqlmigrationsResource = v1alpha1.SchemeGroupVersion.WithResource("mysqlmigrations")

var mysqlmigrationsKind = v1alpha1.SchemeGroupVersion.WithKind("MySQLMigration")

// Get takes name of the mySQLMigration, and returns the corresponding mySQLMigration object, and an error if there is any.
func (c *FakeMySQLMigrations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MySQLMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mysqlmigrationsResource, c.ns, name), &v1alpha1.MySQLMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLMigration), err
}

// List takes label and field selectors, and returns the list of MySQLMigrations that match those selectors.
func (c *FakeMySQLMigrations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MySQLMigrationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mysqlmigrationsResource, mysqlmigrationsKind, c.ns, opts), &v1alpha1.MySQLMigrationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MySQLMigrationList{ListMeta: obj.(*v1alpha1.MySQLMigrationList).ListMeta}
	for _, item := range obj.(*v1alpha1.MySQLMigrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mySQLMigrations.
func (c *FakeMySQLMigrations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mysqlmigrationsResource, c.ns, opts))

}

// Create takes the representation of a mySQLMigration and creates it.  Returns the server's representation of the mySQLMigration, and an error, if there is any.
func (c *FakeMySQLMigrations) Create(ctx context.Context, mySQLMigration *v1alpha1.MySQLMigration, opts v1.CreateOptions) (result *v1alpha1.MySQLMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mysqlmigrationsResource, c.ns, mySQLMigration), &v1alpha1.MySQLMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLMigration), err
}

// Update takes the representation of a mySQLMigration and updates it. Returns the server's representation of the mySQLMigration, and an error, if there is any.
func (c *FakeMySQLMigrations) Update(ctx context.Context, mySQLMigration *v1alpha1.MySQLMigration, opts v1.UpdateOptions) (result *v1alpha1.MySQLMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mysqlmigrationsResource, c.ns, mySQLMigration), &v1alpha1.MySQLMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLMigration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMySQLMigrations) UpdateStatus(ctx context.Context, mySQLMigration *v1alpha1.MySQLMigration, opts v1.UpdateOptions) (*v1alpha1.MySQLMigration, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mysqlmigrationsResource, "status", c.ns, mySQLMigration), &v1alpha1.MySQLMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLMigration), err
}

// Delete takes name of the mySQLMigration and deletes it. Returns an error if one occurs.
func (c *FakeMySQLMigrations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mysqlmigrationsResource, c.ns, name, opts), &v1alpha1.MySQLMigration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMySQLMigrations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mysqlmigrationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MySQLMigrationList{})
	return err
}

// Patch applies the patch and returns the patched mySQLMigration.
func (c *FakeMySQLMigrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MySQLMigration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mysqlmigrationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MySQLMigration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLMigration), err
}
