/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "kubedb.dev/apimachinery/apis/catalog/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CassandraVersionLister helps list CassandraVersions.
// All objects returned here must be treated as read-only.
type CassandraVersionLister interface {
	// List lists all CassandraVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*catalogv1alpha1.CassandraVersion, err error)
	// Get retrieves the CassandraVersion from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*catalogv1alpha1.CassandraVersion, error)
	CassandraVersionListerExpansion
}

// cassandraVersionLister implements the CassandraVersionLister interface.
type cassandraVersionLister struct {
	listers.ResourceIndexer[*catalogv1alpha1.CassandraVersion]
}

// NewCassandraVersionLister returns a new CassandraVersionLister.
func NewCassandraVersionLister(indexer cache.Indexer) CassandraVersionLister {
	return &cassandraVersionLister{listers.New[*catalogv1alpha1.CassandraVersion](indexer, catalogv1alpha1.Resource("cassandraversion"))}
}
