/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	catalogv1alpha1 "kubedb.dev/apimachinery/apis/catalog/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresVersionLister helps list PostgresVersions.
// All objects returned here must be treated as read-only.
type PostgresVersionLister interface {
	// List lists all PostgresVersions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*catalogv1alpha1.PostgresVersion, err error)
	// Get retrieves the PostgresVersion from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*catalogv1alpha1.PostgresVersion, error)
	PostgresVersionListerExpansion
}

// postgresVersionLister implements the PostgresVersionLister interface.
type postgresVersionLister struct {
	listers.ResourceIndexer[*catalogv1alpha1.PostgresVersion]
}

// NewPostgresVersionLister returns a new PostgresVersionLister.
func NewPostgresVersionLister(indexer cache.Indexer) PostgresVersionLister {
	return &postgresVersionLister{listers.New[*catalogv1alpha1.PostgresVersion](indexer, catalogv1alpha1.Resource("postgresversion"))}
}
