// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: migration.proto

package migrator

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{0}
}

type MigrationProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Database type: postgres / mongodb / mariadb
	DbType        string           `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	Details       *structpb.Struct `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrationProgress) Reset() {
	*x = MigrationProgress{}
	mi := &file_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationProgress) ProtoMessage() {}

func (x *MigrationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationProgress.ProtoReflect.Descriptor instead.
func (*MigrationProgress) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationProgress) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *MigrationProgress) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

type DestroyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific database type to destroy, if empty destroys current migration
	DbType        string `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyRequest) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_migration_proto_rawDescGZIP(), []int{3}
}

func (x *DestroyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_migration_proto protoreflect.FileDescriptor

const file_migration_proto_rawDesc = "" +
	"\n" +
	"\x0fmigration.proto\x12\bmigrator\x1a\x1cgoogle/protobuf/struct.proto\"\x14\n" +
	"\x12GetProgressRequest\"_\n" +
	"\x11MigrationProgress\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x121\n" +
	"\adetails\x18\x03 \x01(\v2\x17.google.protobuf.StructR\adetails\")\n" +
	"\x0eDestroyRequest\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\"E\n" +
	"\x0fDestroyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x84\x02\n" +
	"\x10MigrationService\x12V\n" +
	"\x17StreamMigrationProgress\x12\x1c.migrator.GetProgressRequest\x1a\x1b.migrator.MigrationProgress0\x01\x12O\n" +
	"\x12GetCurrentProgress\x12\x1c.migrator.GetProgressRequest\x1a\x1b.migrator.MigrationProgress\x12G\n" +
	"\x10DestroyMigration\x12\x18.migrator.DestroyRequest\x1a\x19.migrator.DestroyResponseB'Z%kubedb.dev/migrator/pkg/grpc/proto;pbb\x06proto3"

var (
	file_migration_proto_rawDescOnce sync.Once
	file_migration_proto_rawDescData []byte
)

func file_migration_proto_rawDescGZIP() []byte {
	file_migration_proto_rawDescOnce.Do(func() {
		file_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)))
	})
	return file_migration_proto_rawDescData
}

var file_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_migration_proto_goTypes = []any{
	(*GetProgressRequest)(nil), // 0: migrator.GetProgressRequest
	(*MigrationProgress)(nil),  // 1: migrator.MigrationProgress
	(*DestroyRequest)(nil),     // 2: migrator.DestroyRequest
	(*DestroyResponse)(nil),    // 3: migrator.DestroyResponse
	(*structpb.Struct)(nil),    // 4: google.protobuf.Struct
}
var file_migration_proto_depIdxs = []int32{
	4, // 0: migrator.MigrationProgress.details:type_name -> google.protobuf.Struct
	0, // 1: migrator.MigrationService.StreamMigrationProgress:input_type -> migrator.GetProgressRequest
	0, // 2: migrator.MigrationService.GetCurrentProgress:input_type -> migrator.GetProgressRequest
	2, // 3: migrator.MigrationService.DestroyMigration:input_type -> migrator.DestroyRequest
	1, // 4: migrator.MigrationService.StreamMigrationProgress:output_type -> migrator.MigrationProgress
	1, // 5: migrator.MigrationService.GetCurrentProgress:output_type -> migrator.MigrationProgress
	3, // 6: migrator.MigrationService.DestroyMigration:output_type -> migrator.DestroyResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_migration_proto_init() }
func file_migration_proto_init() {
	if File_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migration_proto_rawDesc), len(file_migration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migration_proto_goTypes,
		DependencyIndexes: file_migration_proto_depIdxs,
		MessageInfos:      file_migration_proto_msgTypes,
	}.Build()
	File_migration_proto = out.File
	file_migration_proto_goTypes = nil
	file_migration_proto_depIdxs = nil
}
