/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubedbv1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MySQLLister helps list MySQLs.
// All objects returned here must be treated as read-only.
type MySQLLister interface {
	// List lists all MySQLs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1alpha2.MySQL, err error)
	// MySQLs returns an object that can list and get MySQLs.
	MySQLs(namespace string) MySQLNamespaceLister
	MySQLListerExpansion
}

// mySQLLister implements the MySQLLister interface.
type mySQLLister struct {
	listers.ResourceIndexer[*kubedbv1alpha2.MySQL]
}

// NewMySQLLister returns a new MySQLLister.
func NewMySQLLister(indexer cache.Indexer) MySQLLister {
	return &mySQLLister{listers.New[*kubedbv1alpha2.MySQL](indexer, kubedbv1alpha2.Resource("mysql"))}
}

// MySQLs returns an object that can list and get MySQLs.
func (s *mySQLLister) MySQLs(namespace string) MySQLNamespaceLister {
	return mySQLNamespaceLister{listers.NewNamespaced[*kubedbv1alpha2.MySQL](s.ResourceIndexer, namespace)}
}

// MySQLNamespaceLister helps list and get MySQLs.
// All objects returned here must be treated as read-only.
type MySQLNamespaceLister interface {
	// List lists all MySQLs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1alpha2.MySQL, err error)
	// Get retrieves the MySQL from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubedbv1alpha2.MySQL, error)
	MySQLNamespaceListerExpansion
}

// mySQLNamespaceLister implements the MySQLNamespaceLister
// interface.
type mySQLNamespaceLister struct {
	listers.ResourceIndexer[*kubedbv1alpha2.MySQL]
}
