/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubedbv1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OracleLister helps list Oracles.
// All objects returned here must be treated as read-only.
type OracleLister interface {
	// List lists all Oracles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1alpha2.Oracle, err error)
	// Oracles returns an object that can list and get Oracles.
	Oracles(namespace string) OracleNamespaceLister
	OracleListerExpansion
}

// oracleLister implements the OracleLister interface.
type oracleLister struct {
	listers.ResourceIndexer[*kubedbv1alpha2.Oracle]
}

// NewOracleLister returns a new OracleLister.
func NewOracleLister(indexer cache.Indexer) OracleLister {
	return &oracleLister{listers.New[*kubedbv1alpha2.Oracle](indexer, kubedbv1alpha2.Resource("oracle"))}
}

// Oracles returns an object that can list and get Oracles.
func (s *oracleLister) Oracles(namespace string) OracleNamespaceLister {
	return oracleNamespaceLister{listers.NewNamespaced[*kubedbv1alpha2.Oracle](s.ResourceIndexer, namespace)}
}

// OracleNamespaceLister helps list and get Oracles.
// All objects returned here must be treated as read-only.
type OracleNamespaceLister interface {
	// List lists all Oracles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1alpha2.Oracle, err error)
	// Get retrieves the Oracle from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubedbv1alpha2.Oracle, error)
	OracleNamespaceListerExpansion
}

// oracleNamespaceLister implements the OracleNamespaceLister
// interface.
type oracleNamespaceLister struct {
	listers.ResourceIndexer[*kubedbv1alpha2.Oracle]
}
