/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RabbitmqLister helps list Rabbitmqs.
// All objects returned here must be treated as read-only.
type RabbitmqLister interface {
	// List lists all Rabbitmqs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.Rabbitmq, err error)
	// Rabbitmqs returns an object that can list and get Rabbitmqs.
	Rabbitmqs(namespace string) RabbitmqNamespaceLister
	RabbitmqListerExpansion
}

// rabbitmqLister implements the RabbitmqLister interface.
type rabbitmqLister struct {
	indexer cache.Indexer
}

// NewRabbitmqLister returns a new RabbitmqLister.
func NewRabbitmqLister(indexer cache.Indexer) RabbitmqLister {
	return &rabbitmqLister{indexer: indexer}
}

// List lists all Rabbitmqs in the indexer.
func (s *rabbitmqLister) List(selector labels.Selector) (ret []*v1alpha2.Rabbitmq, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.Rabbitmq))
	})
	return ret, err
}

// Rabbitmqs returns an object that can list and get Rabbitmqs.
func (s *rabbitmqLister) Rabbitmqs(namespace string) RabbitmqNamespaceLister {
	return rabbitmqNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RabbitmqNamespaceLister helps list and get Rabbitmqs.
// All objects returned here must be treated as read-only.
type RabbitmqNamespaceLister interface {
	// List lists all Rabbitmqs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.Rabbitmq, err error)
	// Get retrieves the Rabbitmq from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.Rabbitmq, error)
	RabbitmqNamespaceListerExpansion
}

// rabbitmqNamespaceLister implements the RabbitmqNamespaceLister
// interface.
type rabbitmqNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Rabbitmqs in the indexer for a given namespace.
func (s rabbitmqNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.Rabbitmq, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.Rabbitmq))
	})
	return ret, err
}

// Get retrieves the Rabbitmq from the indexer for a given namespace and name.
func (s rabbitmqNamespaceLister) Get(name string) (*v1alpha2.Rabbitmq, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("rabbitmq"), name)
	}
	return obj.(*v1alpha2.Rabbitmq), nil
}
