/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AerospikeAutoscalerLister helps list AerospikeAutoscalers.
// All objects returned here must be treated as read-only.
type AerospikeAutoscalerLister interface {
	// List lists all AerospikeAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AerospikeAutoscaler, err error)
	// AerospikeAutoscalers returns an object that can list and get AerospikeAutoscalers.
	AerospikeAutoscalers(namespace string) AerospikeAutoscalerNamespaceLister
	AerospikeAutoscalerListerExpansion
}

// aerospikeAutoscalerLister implements the AerospikeAutoscalerLister interface.
type aerospikeAutoscalerLister struct {
	indexer cache.Indexer
}

// NewAerospikeAutoscalerLister returns a new AerospikeAutoscalerLister.
func NewAerospikeAutoscalerLister(indexer cache.Indexer) AerospikeAutoscalerLister {
	return &aerospikeAutoscalerLister{indexer: indexer}
}

// List lists all AerospikeAutoscalers in the indexer.
func (s *aerospikeAutoscalerLister) List(selector labels.Selector) (ret []*v1alpha1.AerospikeAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AerospikeAutoscaler))
	})
	return ret, err
}

// AerospikeAutoscalers returns an object that can list and get AerospikeAutoscalers.
func (s *aerospikeAutoscalerLister) AerospikeAutoscalers(namespace string) AerospikeAutoscalerNamespaceLister {
	return aerospikeAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AerospikeAutoscalerNamespaceLister helps list and get AerospikeAutoscalers.
// All objects returned here must be treated as read-only.
type AerospikeAutoscalerNamespaceLister interface {
	// List lists all AerospikeAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.AerospikeAutoscaler, err error)
	// Get retrieves the AerospikeAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.AerospikeAutoscaler, error)
	AerospikeAutoscalerNamespaceListerExpansion
}

// aerospikeAutoscalerNamespaceLister implements the AerospikeAutoscalerNamespaceLister
// interface.
type aerospikeAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AerospikeAutoscalers in the indexer for a given namespace.
func (s aerospikeAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.AerospikeAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.AerospikeAutoscaler))
	})
	return ret, err
}

// Get retrieves the AerospikeAutoscaler from the indexer for a given namespace and name.
func (s aerospikeAutoscalerNamespaceLister) Get(name string) (*v1alpha1.AerospikeAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("aerospikeautoscaler"), name)
	}
	return obj.(*v1alpha1.AerospikeAutoscaler), nil
}
