/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DB2AutoscalerLister helps list DB2Autoscalers.
// All objects returned here must be treated as read-only.
type DB2AutoscalerLister interface {
	// List lists all DB2Autoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.DB2Autoscaler, err error)
	// DB2Autoscalers returns an object that can list and get DB2Autoscalers.
	DB2Autoscalers(namespace string) DB2AutoscalerNamespaceLister
	DB2AutoscalerListerExpansion
}

// dB2AutoscalerLister implements the DB2AutoscalerLister interface.
type dB2AutoscalerLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.DB2Autoscaler]
}

// NewDB2AutoscalerLister returns a new DB2AutoscalerLister.
func NewDB2AutoscalerLister(indexer cache.Indexer) DB2AutoscalerLister {
	return &dB2AutoscalerLister{listers.New[*autoscalingv1alpha1.DB2Autoscaler](indexer, autoscalingv1alpha1.Resource("db2autoscaler"))}
}

// DB2Autoscalers returns an object that can list and get DB2Autoscalers.
func (s *dB2AutoscalerLister) DB2Autoscalers(namespace string) DB2AutoscalerNamespaceLister {
	return dB2AutoscalerNamespaceLister{listers.NewNamespaced[*autoscalingv1alpha1.DB2Autoscaler](s.ResourceIndexer, namespace)}
}

// DB2AutoscalerNamespaceLister helps list and get DB2Autoscalers.
// All objects returned here must be treated as read-only.
type DB2AutoscalerNamespaceLister interface {
	// List lists all DB2Autoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.DB2Autoscaler, err error)
	// Get retrieves the DB2Autoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingv1alpha1.DB2Autoscaler, error)
	DB2AutoscalerNamespaceListerExpansion
}

// dB2AutoscalerNamespaceLister implements the DB2AutoscalerNamespaceLister
// interface.
type dB2AutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.DB2Autoscaler]
}
