/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DocumentDBAutoscalerLister helps list DocumentDBAutoscalers.
// All objects returned here must be treated as read-only.
type DocumentDBAutoscalerLister interface {
	// List lists all DocumentDBAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.DocumentDBAutoscaler, err error)
	// DocumentDBAutoscalers returns an object that can list and get DocumentDBAutoscalers.
	DocumentDBAutoscalers(namespace string) DocumentDBAutoscalerNamespaceLister
	DocumentDBAutoscalerListerExpansion
}

// documentDBAutoscalerLister implements the DocumentDBAutoscalerLister interface.
type documentDBAutoscalerLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.DocumentDBAutoscaler]
}

// NewDocumentDBAutoscalerLister returns a new DocumentDBAutoscalerLister.
func NewDocumentDBAutoscalerLister(indexer cache.Indexer) DocumentDBAutoscalerLister {
	return &documentDBAutoscalerLister{listers.New[*autoscalingv1alpha1.DocumentDBAutoscaler](indexer, autoscalingv1alpha1.Resource("documentdbautoscaler"))}
}

// DocumentDBAutoscalers returns an object that can list and get DocumentDBAutoscalers.
func (s *documentDBAutoscalerLister) DocumentDBAutoscalers(namespace string) DocumentDBAutoscalerNamespaceLister {
	return documentDBAutoscalerNamespaceLister{listers.NewNamespaced[*autoscalingv1alpha1.DocumentDBAutoscaler](s.ResourceIndexer, namespace)}
}

// DocumentDBAutoscalerNamespaceLister helps list and get DocumentDBAutoscalers.
// All objects returned here must be treated as read-only.
type DocumentDBAutoscalerNamespaceLister interface {
	// List lists all DocumentDBAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.DocumentDBAutoscaler, err error)
	// Get retrieves the DocumentDBAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingv1alpha1.DocumentDBAutoscaler, error)
	DocumentDBAutoscalerNamespaceListerExpansion
}

// documentDBAutoscalerNamespaceLister implements the DocumentDBAutoscalerNamespaceLister
// interface.
type documentDBAutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.DocumentDBAutoscaler]
}
