/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MariaDBAutoscalerLister helps list MariaDBAutoscalers.
// All objects returned here must be treated as read-only.
type MariaDBAutoscalerLister interface {
	// List lists all MariaDBAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.MariaDBAutoscaler, err error)
	// MariaDBAutoscalers returns an object that can list and get MariaDBAutoscalers.
	MariaDBAutoscalers(namespace string) MariaDBAutoscalerNamespaceLister
	MariaDBAutoscalerListerExpansion
}

// mariaDBAutoscalerLister implements the MariaDBAutoscalerLister interface.
type mariaDBAutoscalerLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.MariaDBAutoscaler]
}

// NewMariaDBAutoscalerLister returns a new MariaDBAutoscalerLister.
func NewMariaDBAutoscalerLister(indexer cache.Indexer) MariaDBAutoscalerLister {
	return &mariaDBAutoscalerLister{listers.New[*autoscalingv1alpha1.MariaDBAutoscaler](indexer, autoscalingv1alpha1.Resource("mariadbautoscaler"))}
}

// MariaDBAutoscalers returns an object that can list and get MariaDBAutoscalers.
func (s *mariaDBAutoscalerLister) MariaDBAutoscalers(namespace string) MariaDBAutoscalerNamespaceLister {
	return mariaDBAutoscalerNamespaceLister{listers.NewNamespaced[*autoscalingv1alpha1.MariaDBAutoscaler](s.ResourceIndexer, namespace)}
}

// MariaDBAutoscalerNamespaceLister helps list and get MariaDBAutoscalers.
// All objects returned here must be treated as read-only.
type MariaDBAutoscalerNamespaceLister interface {
	// List lists all MariaDBAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.MariaDBAutoscaler, err error)
	// Get retrieves the MariaDBAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingv1alpha1.MariaDBAutoscaler, error)
	MariaDBAutoscalerNamespaceListerExpansion
}

// mariaDBAutoscalerNamespaceLister implements the MariaDBAutoscalerNamespaceLister
// interface.
type mariaDBAutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.MariaDBAutoscaler]
}
