/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
)

// MilvusAutoscalerLister helps list MilvusAutoscalers.
// All objects returned here must be treated as read-only.
type MilvusAutoscalerLister interface {
	// List lists all MilvusAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusAutoscaler, err error)
	// MilvusAutoscalers returns an object that can list and get MilvusAutoscalers.
	MilvusAutoscalers(namespace string) MilvusAutoscalerNamespaceLister
	MilvusAutoscalerListerExpansion
}

// milvusAutoscalerLister implements the MilvusAutoscalerLister interface.
type milvusAutoscalerLister struct {
	indexer cache.Indexer
}

// NewMilvusAutoscalerLister returns a new MilvusAutoscalerLister.
func NewMilvusAutoscalerLister(indexer cache.Indexer) MilvusAutoscalerLister {
	return &milvusAutoscalerLister{indexer: indexer}
}

// List lists all MilvusAutoscalers in the indexer.
func (s *milvusAutoscalerLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusAutoscaler))
	})
	return ret, err
}

// MilvusAutoscalers returns an object that can list and get MilvusAutoscalers.
func (s *milvusAutoscalerLister) MilvusAutoscalers(namespace string) MilvusAutoscalerNamespaceLister {
	return milvusAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MilvusAutoscalerNamespaceLister helps list and get MilvusAutoscalers.
// All objects returned here must be treated as read-only.
type MilvusAutoscalerNamespaceLister interface {
	// List lists all MilvusAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusAutoscaler, err error)
	// Get retrieves the MilvusAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MilvusAutoscaler, error)
	MilvusAutoscalerNamespaceListerExpansion
}

// milvusAutoscalerNamespaceLister implements the MilvusAutoscalerNamespaceLister
// interface.
type milvusAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MilvusAutoscalers in the indexer for a given namespace.
func (s milvusAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusAutoscaler))
	})
	return ret, err
}

// Get retrieves the MilvusAutoscaler from the indexer for a given namespace and name.
func (s milvusAutoscalerNamespaceLister) Get(name string) (*v1alpha1.MilvusAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("milvusautoscaler"), name)
	}
	return obj.(*v1alpha1.MilvusAutoscaler), nil
}
