/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
)

// Neo4jAutoscalerLister helps list Neo4jAutoscalers.
// All objects returned here must be treated as read-only.
type Neo4jAutoscalerLister interface {
	// List lists all Neo4jAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Neo4jAutoscaler, err error)
	// Neo4jAutoscalers returns an object that can list and get Neo4jAutoscalers.
	Neo4jAutoscalers(namespace string) Neo4jAutoscalerNamespaceLister
	Neo4jAutoscalerListerExpansion
}

// neo4jAutoscalerLister implements the Neo4jAutoscalerLister interface.
type neo4jAutoscalerLister struct {
	indexer cache.Indexer
}

// NewNeo4jAutoscalerLister returns a new Neo4jAutoscalerLister.
func NewNeo4jAutoscalerLister(indexer cache.Indexer) Neo4jAutoscalerLister {
	return &neo4jAutoscalerLister{indexer: indexer}
}

// List lists all Neo4jAutoscalers in the indexer.
func (s *neo4jAutoscalerLister) List(selector labels.Selector) (ret []*v1alpha1.Neo4jAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Neo4jAutoscaler))
	})
	return ret, err
}

// Neo4jAutoscalers returns an object that can list and get Neo4jAutoscalers.
func (s *neo4jAutoscalerLister) Neo4jAutoscalers(namespace string) Neo4jAutoscalerNamespaceLister {
	return neo4jAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// Neo4jAutoscalerNamespaceLister helps list and get Neo4jAutoscalers.
// All objects returned here must be treated as read-only.
type Neo4jAutoscalerNamespaceLister interface {
	// List lists all Neo4jAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Neo4jAutoscaler, err error)
	// Get retrieves the Neo4jAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Neo4jAutoscaler, error)
	Neo4jAutoscalerNamespaceListerExpansion
}

// neo4jAutoscalerNamespaceLister implements the Neo4jAutoscalerNamespaceLister
// interface.
type neo4jAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all Neo4jAutoscalers in the indexer for a given namespace.
func (s neo4jAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.Neo4jAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Neo4jAutoscaler))
	})
	return ret, err
}

// Get retrieves the Neo4jAutoscaler from the indexer for a given namespace and name.
func (s neo4jAutoscalerNamespaceLister) Get(name string) (*v1alpha1.Neo4jAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("neo4jautoscaler"), name)
	}
	return obj.(*v1alpha1.Neo4jAutoscaler), nil
}
