/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
)

// OracleAutoscalerLister helps list OracleAutoscalers.
// All objects returned here must be treated as read-only.
type OracleAutoscalerLister interface {
	// List lists all OracleAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OracleAutoscaler, err error)
	// OracleAutoscalers returns an object that can list and get OracleAutoscalers.
	OracleAutoscalers(namespace string) OracleAutoscalerNamespaceLister
	OracleAutoscalerListerExpansion
}

// oracleAutoscalerLister implements the OracleAutoscalerLister interface.
type oracleAutoscalerLister struct {
	indexer cache.Indexer
}

// NewOracleAutoscalerLister returns a new OracleAutoscalerLister.
func NewOracleAutoscalerLister(indexer cache.Indexer) OracleAutoscalerLister {
	return &oracleAutoscalerLister{indexer: indexer}
}

// List lists all OracleAutoscalers in the indexer.
func (s *oracleAutoscalerLister) List(selector labels.Selector) (ret []*v1alpha1.OracleAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OracleAutoscaler))
	})
	return ret, err
}

// OracleAutoscalers returns an object that can list and get OracleAutoscalers.
func (s *oracleAutoscalerLister) OracleAutoscalers(namespace string) OracleAutoscalerNamespaceLister {
	return oracleAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// OracleAutoscalerNamespaceLister helps list and get OracleAutoscalers.
// All objects returned here must be treated as read-only.
type OracleAutoscalerNamespaceLister interface {
	// List lists all OracleAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OracleAutoscaler, err error)
	// Get retrieves the OracleAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.OracleAutoscaler, error)
	OracleAutoscalerNamespaceListerExpansion
}

// oracleAutoscalerNamespaceLister implements the OracleAutoscalerNamespaceLister
// interface.
type oracleAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all OracleAutoscalers in the indexer for a given namespace.
func (s oracleAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.OracleAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OracleAutoscaler))
	})
	return ret, err
}

// Get retrieves the OracleAutoscaler from the indexer for a given namespace and name.
func (s oracleAutoscalerNamespaceLister) Get(name string) (*v1alpha1.OracleAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("oracleautoscaler"), name)
	}
	return obj.(*v1alpha1.OracleAutoscaler), nil
}
