/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
)

// QdrantAutoscalerLister helps list QdrantAutoscalers.
// All objects returned here must be treated as read-only.
type QdrantAutoscalerLister interface {
	// List lists all QdrantAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.QdrantAutoscaler, err error)
	// QdrantAutoscalers returns an object that can list and get QdrantAutoscalers.
	QdrantAutoscalers(namespace string) QdrantAutoscalerNamespaceLister
	QdrantAutoscalerListerExpansion
}

// qdrantAutoscalerLister implements the QdrantAutoscalerLister interface.
type qdrantAutoscalerLister struct {
	indexer cache.Indexer
}

// NewQdrantAutoscalerLister returns a new QdrantAutoscalerLister.
func NewQdrantAutoscalerLister(indexer cache.Indexer) QdrantAutoscalerLister {
	return &qdrantAutoscalerLister{indexer: indexer}
}

// List lists all QdrantAutoscalers in the indexer.
func (s *qdrantAutoscalerLister) List(selector labels.Selector) (ret []*v1alpha1.QdrantAutoscaler, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.QdrantAutoscaler))
	})
	return ret, err
}

// QdrantAutoscalers returns an object that can list and get QdrantAutoscalers.
func (s *qdrantAutoscalerLister) QdrantAutoscalers(namespace string) QdrantAutoscalerNamespaceLister {
	return qdrantAutoscalerNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// QdrantAutoscalerNamespaceLister helps list and get QdrantAutoscalers.
// All objects returned here must be treated as read-only.
type QdrantAutoscalerNamespaceLister interface {
	// List lists all QdrantAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.QdrantAutoscaler, err error)
	// Get retrieves the QdrantAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.QdrantAutoscaler, error)
	QdrantAutoscalerNamespaceListerExpansion
}

// qdrantAutoscalerNamespaceLister implements the QdrantAutoscalerNamespaceLister
// interface.
type qdrantAutoscalerNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all QdrantAutoscalers in the indexer for a given namespace.
func (s qdrantAutoscalerNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.QdrantAutoscaler, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.QdrantAutoscaler))
	})
	return ret, err
}

// Get retrieves the QdrantAutoscaler from the indexer for a given namespace and name.
func (s qdrantAutoscalerNamespaceLister) Get(name string) (*v1alpha1.QdrantAutoscaler, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("qdrantautoscaler"), name)
	}
	return obj.(*v1alpha1.QdrantAutoscaler), nil
}
