/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ZooKeeperAutoscalerLister helps list ZooKeeperAutoscalers.
// All objects returned here must be treated as read-only.
type ZooKeeperAutoscalerLister interface {
	// List lists all ZooKeeperAutoscalers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.ZooKeeperAutoscaler, err error)
	// ZooKeeperAutoscalers returns an object that can list and get ZooKeeperAutoscalers.
	ZooKeeperAutoscalers(namespace string) ZooKeeperAutoscalerNamespaceLister
	ZooKeeperAutoscalerListerExpansion
}

// zooKeeperAutoscalerLister implements the ZooKeeperAutoscalerLister interface.
type zooKeeperAutoscalerLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.ZooKeeperAutoscaler]
}

// NewZooKeeperAutoscalerLister returns a new ZooKeeperAutoscalerLister.
func NewZooKeeperAutoscalerLister(indexer cache.Indexer) ZooKeeperAutoscalerLister {
	return &zooKeeperAutoscalerLister{listers.New[*autoscalingv1alpha1.ZooKeeperAutoscaler](indexer, autoscalingv1alpha1.Resource("zookeeperautoscaler"))}
}

// ZooKeeperAutoscalers returns an object that can list and get ZooKeeperAutoscalers.
func (s *zooKeeperAutoscalerLister) ZooKeeperAutoscalers(namespace string) ZooKeeperAutoscalerNamespaceLister {
	return zooKeeperAutoscalerNamespaceLister{listers.NewNamespaced[*autoscalingv1alpha1.ZooKeeperAutoscaler](s.ResourceIndexer, namespace)}
}

// ZooKeeperAutoscalerNamespaceLister helps list and get ZooKeeperAutoscalers.
// All objects returned here must be treated as read-only.
type ZooKeeperAutoscalerNamespaceLister interface {
	// List lists all ZooKeeperAutoscalers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*autoscalingv1alpha1.ZooKeeperAutoscaler, err error)
	// Get retrieves the ZooKeeperAutoscaler from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*autoscalingv1alpha1.ZooKeeperAutoscaler, error)
	ZooKeeperAutoscalerNamespaceListerExpansion
}

// zooKeeperAutoscalerNamespaceLister implements the ZooKeeperAutoscalerNamespaceLister
// interface.
type zooKeeperAutoscalerNamespaceLister struct {
	listers.ResourceIndexer[*autoscalingv1alpha1.ZooKeeperAutoscaler]
}
