/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	catalogv1alpha1 "kubedb.dev/apimachinery/apis/catalog/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PgBouncerVersionsGetter has a method to return a PgBouncerVersionInterface.
// A group's client should implement this interface.
type PgBouncerVersionsGetter interface {
	PgBouncerVersions() PgBouncerVersionInterface
}

// PgBouncerVersionInterface has methods to work with PgBouncerVersion resources.
type PgBouncerVersionInterface interface {
	Create(ctx context.Context, pgBouncerVersion *catalogv1alpha1.PgBouncerVersion, opts v1.CreateOptions) (*catalogv1alpha1.PgBouncerVersion, error)
	Update(ctx context.Context, pgBouncerVersion *catalogv1alpha1.PgBouncerVersion, opts v1.UpdateOptions) (*catalogv1alpha1.PgBouncerVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*catalogv1alpha1.PgBouncerVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*catalogv1alpha1.PgBouncerVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *catalogv1alpha1.PgBouncerVersion, err error)
	PgBouncerVersionExpansion
}

// pgBouncerVersions implements PgBouncerVersionInterface
type pgBouncerVersions struct {
	*gentype.ClientWithList[*catalogv1alpha1.PgBouncerVersion, *catalogv1alpha1.PgBouncerVersionList]
}

// newPgBouncerVersions returns a PgBouncerVersions
func newPgBouncerVersions(c *CatalogV1alpha1Client) *pgBouncerVersions {
	return &pgBouncerVersions{
		gentype.NewClientWithList[*catalogv1alpha1.PgBouncerVersion, *catalogv1alpha1.PgBouncerVersionList](
			"pgbouncerversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *catalogv1alpha1.PgBouncerVersion { return &catalogv1alpha1.PgBouncerVersion{} },
			func() *catalogv1alpha1.PgBouncerVersionList { return &catalogv1alpha1.PgBouncerVersionList{} },
		),
	}
}
