/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	catalogv1alpha1 "kubedb.dev/apimachinery/apis/catalog/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WeaviateVersionsGetter has a method to return a WeaviateVersionInterface.
// A group's client should implement this interface.
type WeaviateVersionsGetter interface {
	WeaviateVersions() WeaviateVersionInterface
}

// WeaviateVersionInterface has methods to work with WeaviateVersion resources.
type WeaviateVersionInterface interface {
	Create(ctx context.Context, weaviateVersion *catalogv1alpha1.WeaviateVersion, opts v1.CreateOptions) (*catalogv1alpha1.WeaviateVersion, error)
	Update(ctx context.Context, weaviateVersion *catalogv1alpha1.WeaviateVersion, opts v1.UpdateOptions) (*catalogv1alpha1.WeaviateVersion, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*catalogv1alpha1.WeaviateVersion, error)
	List(ctx context.Context, opts v1.ListOptions) (*catalogv1alpha1.WeaviateVersionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *catalogv1alpha1.WeaviateVersion, err error)
	WeaviateVersionExpansion
}

// weaviateVersions implements WeaviateVersionInterface
type weaviateVersions struct {
	*gentype.ClientWithList[*catalogv1alpha1.WeaviateVersion, *catalogv1alpha1.WeaviateVersionList]
}

// newWeaviateVersions returns a WeaviateVersions
func newWeaviateVersions(c *CatalogV1alpha1Client) *weaviateVersions {
	return &weaviateVersions{
		gentype.NewClientWithList[*catalogv1alpha1.WeaviateVersion, *catalogv1alpha1.WeaviateVersionList](
			"weaviateversions",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *catalogv1alpha1.WeaviateVersion { return &catalogv1alpha1.WeaviateVersion{} },
			func() *catalogv1alpha1.WeaviateVersionList { return &catalogv1alpha1.WeaviateVersionList{} },
		),
	}
}
