/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubedb.dev/apimachinery/client/clientset/versioned/typed/catalog/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCatalogV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCatalogV1alpha1) AerospikeVersions() v1alpha1.AerospikeVersionInterface {
	return newFakeAerospikeVersions(c)
}

func (c *FakeCatalogV1alpha1) CassandraVersions() v1alpha1.CassandraVersionInterface {
	return newFakeCassandraVersions(c)
}

func (c *FakeCatalogV1alpha1) ClickHouseVersions() v1alpha1.ClickHouseVersionInterface {
	return newFakeClickHouseVersions(c)
}

func (c *FakeCatalogV1alpha1) DB2Versions() v1alpha1.DB2VersionInterface {
	return newFakeDB2Versions(c)
}

func (c *FakeCatalogV1alpha1) DocumentDBVersions() v1alpha1.DocumentDBVersionInterface {
	return newFakeDocumentDBVersions(c)
}

func (c *FakeCatalogV1alpha1) DruidVersions() v1alpha1.DruidVersionInterface {
	return newFakeDruidVersions(c)
}

func (c *FakeCatalogV1alpha1) ElasticsearchVersions() v1alpha1.ElasticsearchVersionInterface {
	return newFakeElasticsearchVersions(c)
}

func (c *FakeCatalogV1alpha1) EtcdVersions() v1alpha1.EtcdVersionInterface {
	return newFakeEtcdVersions(c)
}

func (c *FakeCatalogV1alpha1) HanaDBVersions() v1alpha1.HanaDBVersionInterface {
	return newFakeHanaDBVersions(c)
}

func (c *FakeCatalogV1alpha1) HazelcastVersions() v1alpha1.HazelcastVersionInterface {
	return newFakeHazelcastVersions(c)
}

func (c *FakeCatalogV1alpha1) IgniteVersions() v1alpha1.IgniteVersionInterface {
	return newFakeIgniteVersions(c)
}

func (c *FakeCatalogV1alpha1) KafkaConnectorVersions() v1alpha1.KafkaConnectorVersionInterface {
	return newFakeKafkaConnectorVersions(c)
}

func (c *FakeCatalogV1alpha1) KafkaVersions() v1alpha1.KafkaVersionInterface {
	return newFakeKafkaVersions(c)
}

func (c *FakeCatalogV1alpha1) MSSQLServerVersions() v1alpha1.MSSQLServerVersionInterface {
	return newFakeMSSQLServerVersions(c)
}

func (c *FakeCatalogV1alpha1) MariaDBVersions() v1alpha1.MariaDBVersionInterface {
	return newFakeMariaDBVersions(c)
}

func (c *FakeCatalogV1alpha1) MemcachedVersions() v1alpha1.MemcachedVersionInterface {
	return newFakeMemcachedVersions(c)
}

func (c *FakeCatalogV1alpha1) MilvusVersions() v1alpha1.MilvusVersionInterface {
	return newFakeMilvusVersions(c)
}

func (c *FakeCatalogV1alpha1) MongoDBVersions() v1alpha1.MongoDBVersionInterface {
	return newFakeMongoDBVersions(c)
}

func (c *FakeCatalogV1alpha1) MySQLVersions() v1alpha1.MySQLVersionInterface {
	return newFakeMySQLVersions(c)
}

func (c *FakeCatalogV1alpha1) Neo4jVersions() v1alpha1.Neo4jVersionInterface {
	return newFakeNeo4jVersions(c)
}

func (c *FakeCatalogV1alpha1) OracleVersions() v1alpha1.OracleVersionInterface {
	return newFakeOracleVersions(c)
}

func (c *FakeCatalogV1alpha1) PerconaXtraDBVersions() v1alpha1.PerconaXtraDBVersionInterface {
	return newFakePerconaXtraDBVersions(c)
}

func (c *FakeCatalogV1alpha1) PgBouncerVersions() v1alpha1.PgBouncerVersionInterface {
	return newFakePgBouncerVersions(c)
}

func (c *FakeCatalogV1alpha1) PgpoolVersions() v1alpha1.PgpoolVersionInterface {
	return newFakePgpoolVersions(c)
}

func (c *FakeCatalogV1alpha1) PostgresVersions() v1alpha1.PostgresVersionInterface {
	return newFakePostgresVersions(c)
}

func (c *FakeCatalogV1alpha1) ProxySQLVersions() v1alpha1.ProxySQLVersionInterface {
	return newFakeProxySQLVersions(c)
}

func (c *FakeCatalogV1alpha1) QdrantVersions() v1alpha1.QdrantVersionInterface {
	return newFakeQdrantVersions(c)
}

func (c *FakeCatalogV1alpha1) RabbitMQVersions() v1alpha1.RabbitMQVersionInterface {
	return newFakeRabbitMQVersions(c)
}

func (c *FakeCatalogV1alpha1) RedisVersions() v1alpha1.RedisVersionInterface {
	return newFakeRedisVersions(c)
}

func (c *FakeCatalogV1alpha1) SchemaRegistryVersions() v1alpha1.SchemaRegistryVersionInterface {
	return newFakeSchemaRegistryVersions(c)
}

func (c *FakeCatalogV1alpha1) SinglestoreVersions() v1alpha1.SinglestoreVersionInterface {
	return newFakeSinglestoreVersions(c)
}

func (c *FakeCatalogV1alpha1) SolrVersions() v1alpha1.SolrVersionInterface {
	return newFakeSolrVersions(c)
}

func (c *FakeCatalogV1alpha1) WeaviateVersions() v1alpha1.WeaviateVersionInterface {
	return newFakeWeaviateVersions(c)
}

func (c *FakeCatalogV1alpha1) ZooKeeperVersions() v1alpha1.ZooKeeperVersionInterface {
	return newFakeZooKeeperVersions(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCatalogV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
