/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubedb.dev/apimachinery/apis/catalog/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWeaviateVersions implements WeaviateVersionInterface
type FakeWeaviateVersions struct {
	Fake *FakeCatalogV1alpha1
}

var weaviateversionsResource = v1alpha1.SchemeGroupVersion.WithResource("weaviateversions")

var weaviateversionsKind = v1alpha1.SchemeGroupVersion.WithKind("WeaviateVersion")

// Get takes name of the weaviateVersion, and returns the corresponding weaviateVersion object, and an error if there is any.
func (c *FakeWeaviateVersions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WeaviateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(weaviateversionsResource, name), &v1alpha1.WeaviateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateVersion), err
}

// List takes label and field selectors, and returns the list of WeaviateVersions that match those selectors.
func (c *FakeWeaviateVersions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WeaviateVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(weaviateversionsResource, weaviateversionsKind, opts), &v1alpha1.WeaviateVersionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WeaviateVersionList{ListMeta: obj.(*v1alpha1.WeaviateVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.WeaviateVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested weaviateVersions.
func (c *FakeWeaviateVersions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(weaviateversionsResource, opts))
}

// Create takes the representation of a weaviateVersion and creates it.  Returns the server's representation of the weaviateVersion, and an error, if there is any.
func (c *FakeWeaviateVersions) Create(ctx context.Context, weaviateVersion *v1alpha1.WeaviateVersion, opts v1.CreateOptions) (result *v1alpha1.WeaviateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(weaviateversionsResource, weaviateVersion), &v1alpha1.WeaviateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateVersion), err
}

// Update takes the representation of a weaviateVersion and updates it. Returns the server's representation of the weaviateVersion, and an error, if there is any.
func (c *FakeWeaviateVersions) Update(ctx context.Context, weaviateVersion *v1alpha1.WeaviateVersion, opts v1.UpdateOptions) (result *v1alpha1.WeaviateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(weaviateversionsResource, weaviateVersion), &v1alpha1.WeaviateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateVersion), err
}

// Delete takes name of the weaviateVersion and deletes it. Returns an error if one occurs.
func (c *FakeWeaviateVersions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(weaviateversionsResource, name, opts), &v1alpha1.WeaviateVersion{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWeaviateVersions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(weaviateversionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WeaviateVersionList{})
	return err
}

// Patch applies the patch and returns the patched weaviateVersion.
func (c *FakeWeaviateVersions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WeaviateVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(weaviateversionsResource, name, pt, data, subresources...), &v1alpha1.WeaviateVersion{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateVersion), err
}
