/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	kubedbv1 "kubedb.dev/apimachinery/apis/kubedb/v1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PostgresesGetter has a method to return a PostgresInterface.
// A group's client should implement this interface.
type PostgresesGetter interface {
	Postgreses(namespace string) PostgresInterface
}

// PostgresInterface has methods to work with Postgres resources.
type PostgresInterface interface {
	Create(ctx context.Context, postgres *kubedbv1.Postgres, opts metav1.CreateOptions) (*kubedbv1.Postgres, error)
	Update(ctx context.Context, postgres *kubedbv1.Postgres, opts metav1.UpdateOptions) (*kubedbv1.Postgres, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, postgres *kubedbv1.Postgres, opts metav1.UpdateOptions) (*kubedbv1.Postgres, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*kubedbv1.Postgres, error)
	List(ctx context.Context, opts metav1.ListOptions) (*kubedbv1.PostgresList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *kubedbv1.Postgres, err error)
	PostgresExpansion
}

// postgreses implements PostgresInterface
type postgreses struct {
	*gentype.ClientWithList[*kubedbv1.Postgres, *kubedbv1.PostgresList]
}

// newPostgreses returns a Postgreses
func newPostgreses(c *KubedbV1Client, namespace string) *postgreses {
	return &postgreses{
		gentype.NewClientWithList[*kubedbv1.Postgres, *kubedbv1.PostgresList](
			"postgreses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubedbv1.Postgres { return &kubedbv1.Postgres{} },
			func() *kubedbv1.PostgresList { return &kubedbv1.PostgresList{} },
		),
	}
}
