/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	gitopsv1alpha1 "kubedb.dev/apimachinery/apis/gitops/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DB2sGetter has a method to return a DB2Interface.
// A group's client should implement this interface.
type DB2sGetter interface {
	DB2s(namespace string) DB2Interface
}

// DB2Interface has methods to work with DB2 resources.
type DB2Interface interface {
	Create(ctx context.Context, dB2 *gitopsv1alpha1.DB2, opts v1.CreateOptions) (*gitopsv1alpha1.DB2, error)
	Update(ctx context.Context, dB2 *gitopsv1alpha1.DB2, opts v1.UpdateOptions) (*gitopsv1alpha1.DB2, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dB2 *gitopsv1alpha1.DB2, opts v1.UpdateOptions) (*gitopsv1alpha1.DB2, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*gitopsv1alpha1.DB2, error)
	List(ctx context.Context, opts v1.ListOptions) (*gitopsv1alpha1.DB2List, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gitopsv1alpha1.DB2, err error)
	DB2Expansion
}

// dB2s implements DB2Interface
type dB2s struct {
	*gentype.ClientWithList[*gitopsv1alpha1.DB2, *gitopsv1alpha1.DB2List]
}

// newDB2s returns a DB2s
func newDB2s(c *GitopsV1alpha1Client, namespace string) *dB2s {
	return &dB2s{
		gentype.NewClientWithList[*gitopsv1alpha1.DB2, *gitopsv1alpha1.DB2List](
			"db2s",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *gitopsv1alpha1.DB2 { return &gitopsv1alpha1.DB2{} },
			func() *gitopsv1alpha1.DB2List { return &gitopsv1alpha1.DB2List{} },
		),
	}
}
