apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: mongodbmodificationrequests.dba.kubedb.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.type
    name: Type
    type: string
  - JSONPath: .status.phase
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: dba.kubedb.com
  names:
    categories:
    - datastore
    - kubedb
    - appscode
    kind: MongoDBModificationRequest
    listKind: MongoDBModificationRequestList
    plural: mongodbmodificationrequests
    shortNames:
    - mgmodreq
    singular: mongodbmodificationrequest
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MongoDBModificationRequestSpec is the spec for mongodb modification
            request
          properties:
            databaseRef:
              description: Specifies the Elasticsearch reference
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            type:
              description: Specifies the modification request type; ScaleUp, ScaleDown,
                Upgrade etc.
              type: string
            update:
              description: Specifies the field information that needed to be updated
              properties:
                targetVersion:
                  description: Specifies the ElasticsearchVersion object name
                  type: string
              type: object
          required:
          - databaseRef
          - type
          type: object
        status:
          description: MongoDBModificationRequestStatus is the status for mongodb
            modification request
          properties:
            conditions:
              description: Conditions applied to the request, such as approval or
                denial.
              items:
                properties:
                  lastUpdateTime:
                    description: timestamp for the last update to this condition
                    format: date-time
                    type: string
                  message:
                    description: human readable message with details about the request
                      state
                    type: string
                  reason:
                    description: brief reason for the request state
                    type: string
                  type:
                    description: request approval state, currently Approved or Denied.
                    enum:
                    - Approved
                    - Denied
                    type: string
                required:
                - type
                type: object
              type: array
            observedGeneration:
              description: observedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
            phase:
              type: string
            reason:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
