/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	kubedbv1 "kubedb.dev/apimachinery/apis/kubedb/v1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MariaDBLister helps list MariaDBs.
// All objects returned here must be treated as read-only.
type MariaDBLister interface {
	// List lists all MariaDBs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1.MariaDB, err error)
	// MariaDBs returns an object that can list and get MariaDBs.
	MariaDBs(namespace string) MariaDBNamespaceLister
	MariaDBListerExpansion
}

// mariaDBLister implements the MariaDBLister interface.
type mariaDBLister struct {
	listers.ResourceIndexer[*kubedbv1.MariaDB]
}

// NewMariaDBLister returns a new MariaDBLister.
func NewMariaDBLister(indexer cache.Indexer) MariaDBLister {
	return &mariaDBLister{listers.New[*kubedbv1.MariaDB](indexer, kubedbv1.Resource("mariadb"))}
}

// MariaDBs returns an object that can list and get MariaDBs.
func (s *mariaDBLister) MariaDBs(namespace string) MariaDBNamespaceLister {
	return mariaDBNamespaceLister{listers.NewNamespaced[*kubedbv1.MariaDB](s.ResourceIndexer, namespace)}
}

// MariaDBNamespaceLister helps list and get MariaDBs.
// All objects returned here must be treated as read-only.
type MariaDBNamespaceLister interface {
	// List lists all MariaDBs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubedbv1.MariaDB, err error)
	// Get retrieves the MariaDB from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubedbv1.MariaDB, error)
	MariaDBNamespaceListerExpansion
}

// mariaDBNamespaceLister implements the MariaDBNamespaceLister
// interface.
type mariaDBNamespaceLister struct {
	listers.ResourceIndexer[*kubedbv1.MariaDB]
}
