/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	courierv1alpha1 "kubedb.dev/apimachinery/apis/courier/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BranchWorksGetter has a method to return a BranchWorkInterface.
// A group's client should implement this interface.
type BranchWorksGetter interface {
	BranchWorks(namespace string) BranchWorkInterface
}

// BranchWorkInterface has methods to work with BranchWork resources.
type BranchWorkInterface interface {
	Create(ctx context.Context, branchWork *courierv1alpha1.BranchWork, opts v1.CreateOptions) (*courierv1alpha1.BranchWork, error)
	Update(ctx context.Context, branchWork *courierv1alpha1.BranchWork, opts v1.UpdateOptions) (*courierv1alpha1.BranchWork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, branchWork *courierv1alpha1.BranchWork, opts v1.UpdateOptions) (*courierv1alpha1.BranchWork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*courierv1alpha1.BranchWork, error)
	List(ctx context.Context, opts v1.ListOptions) (*courierv1alpha1.BranchWorkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *courierv1alpha1.BranchWork, err error)
	BranchWorkExpansion
}

// branchWorks implements BranchWorkInterface
type branchWorks struct {
	*gentype.ClientWithList[*courierv1alpha1.BranchWork, *courierv1alpha1.BranchWorkList]
}

// newBranchWorks returns a BranchWorks
func newBranchWorks(c *CourierV1alpha1Client, namespace string) *branchWorks {
	return &branchWorks{
		gentype.NewClientWithList[*courierv1alpha1.BranchWork, *courierv1alpha1.BranchWorkList](
			"branchworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *courierv1alpha1.BranchWork { return &courierv1alpha1.BranchWork{} },
			func() *courierv1alpha1.BranchWorkList { return &courierv1alpha1.BranchWorkList{} },
		),
	}
}
