/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	courierv1alpha1 "kubedb.dev/apimachinery/apis/courier/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MariaDBMigrationsGetter has a method to return a MariaDBMigrationInterface.
// A group's client should implement this interface.
type MariaDBMigrationsGetter interface {
	MariaDBMigrations(namespace string) MariaDBMigrationInterface
}

// MariaDBMigrationInterface has methods to work with MariaDBMigration resources.
type MariaDBMigrationInterface interface {
	Create(ctx context.Context, mariaDBMigration *courierv1alpha1.MariaDBMigration, opts v1.CreateOptions) (*courierv1alpha1.MariaDBMigration, error)
	Update(ctx context.Context, mariaDBMigration *courierv1alpha1.MariaDBMigration, opts v1.UpdateOptions) (*courierv1alpha1.MariaDBMigration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, mariaDBMigration *courierv1alpha1.MariaDBMigration, opts v1.UpdateOptions) (*courierv1alpha1.MariaDBMigration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*courierv1alpha1.MariaDBMigration, error)
	List(ctx context.Context, opts v1.ListOptions) (*courierv1alpha1.MariaDBMigrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *courierv1alpha1.MariaDBMigration, err error)
	MariaDBMigrationExpansion
}

// mariaDBMigrations implements MariaDBMigrationInterface
type mariaDBMigrations struct {
	*gentype.ClientWithList[*courierv1alpha1.MariaDBMigration, *courierv1alpha1.MariaDBMigrationList]
}

// newMariaDBMigrations returns a MariaDBMigrations
func newMariaDBMigrations(c *CourierV1alpha1Client, namespace string) *mariaDBMigrations {
	return &mariaDBMigrations{
		gentype.NewClientWithList[*courierv1alpha1.MariaDBMigration, *courierv1alpha1.MariaDBMigrationList](
			"mariadbmigrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *courierv1alpha1.MariaDBMigration { return &courierv1alpha1.MariaDBMigration{} },
			func() *courierv1alpha1.MariaDBMigrationList { return &courierv1alpha1.MariaDBMigrationList{} },
		),
	}
}
