/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	gitopsv1alpha1 "kubedb.dev/apimachinery/apis/gitops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticsearchLister helps list Elasticsearches.
// All objects returned here must be treated as read-only.
type ElasticsearchLister interface {
	// List lists all Elasticsearches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.Elasticsearch, err error)
	// Elasticsearches returns an object that can list and get Elasticsearches.
	Elasticsearches(namespace string) ElasticsearchNamespaceLister
	ElasticsearchListerExpansion
}

// elasticsearchLister implements the ElasticsearchLister interface.
type elasticsearchLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.Elasticsearch]
}

// NewElasticsearchLister returns a new ElasticsearchLister.
func NewElasticsearchLister(indexer cache.Indexer) ElasticsearchLister {
	return &elasticsearchLister{listers.New[*gitopsv1alpha1.Elasticsearch](indexer, gitopsv1alpha1.Resource("elasticsearch"))}
}

// Elasticsearches returns an object that can list and get Elasticsearches.
func (s *elasticsearchLister) Elasticsearches(namespace string) ElasticsearchNamespaceLister {
	return elasticsearchNamespaceLister{listers.NewNamespaced[*gitopsv1alpha1.Elasticsearch](s.ResourceIndexer, namespace)}
}

// ElasticsearchNamespaceLister helps list and get Elasticsearches.
// All objects returned here must be treated as read-only.
type ElasticsearchNamespaceLister interface {
	// List lists all Elasticsearches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.Elasticsearch, err error)
	// Get retrieves the Elasticsearch from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*gitopsv1alpha1.Elasticsearch, error)
	ElasticsearchNamespaceListerExpansion
}

// elasticsearchNamespaceLister implements the ElasticsearchNamespaceLister
// interface.
type elasticsearchNamespaceLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.Elasticsearch]
}
