/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	gitopsv1alpha1 "kubedb.dev/apimachinery/apis/gitops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ProxySQLLister helps list ProxySQLs.
// All objects returned here must be treated as read-only.
type ProxySQLLister interface {
	// List lists all ProxySQLs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.ProxySQL, err error)
	// ProxySQLs returns an object that can list and get ProxySQLs.
	ProxySQLs(namespace string) ProxySQLNamespaceLister
	ProxySQLListerExpansion
}

// proxySQLLister implements the ProxySQLLister interface.
type proxySQLLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.ProxySQL]
}

// NewProxySQLLister returns a new ProxySQLLister.
func NewProxySQLLister(indexer cache.Indexer) ProxySQLLister {
	return &proxySQLLister{listers.New[*gitopsv1alpha1.ProxySQL](indexer, gitopsv1alpha1.Resource("proxysql"))}
}

// ProxySQLs returns an object that can list and get ProxySQLs.
func (s *proxySQLLister) ProxySQLs(namespace string) ProxySQLNamespaceLister {
	return proxySQLNamespaceLister{listers.NewNamespaced[*gitopsv1alpha1.ProxySQL](s.ResourceIndexer, namespace)}
}

// ProxySQLNamespaceLister helps list and get ProxySQLs.
// All objects returned here must be treated as read-only.
type ProxySQLNamespaceLister interface {
	// List lists all ProxySQLs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.ProxySQL, err error)
	// Get retrieves the ProxySQL from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*gitopsv1alpha1.ProxySQL, error)
	ProxySQLNamespaceListerExpansion
}

// proxySQLNamespaceLister implements the ProxySQLNamespaceLister
// interface.
type proxySQLNamespaceLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.ProxySQL]
}
