/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	gitopsv1alpha1 "kubedb.dev/apimachinery/apis/gitops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RedisSentinelLister helps list RedisSentinels.
// All objects returned here must be treated as read-only.
type RedisSentinelLister interface {
	// List lists all RedisSentinels in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.RedisSentinel, err error)
	// RedisSentinels returns an object that can list and get RedisSentinels.
	RedisSentinels(namespace string) RedisSentinelNamespaceLister
	RedisSentinelListerExpansion
}

// redisSentinelLister implements the RedisSentinelLister interface.
type redisSentinelLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.RedisSentinel]
}

// NewRedisSentinelLister returns a new RedisSentinelLister.
func NewRedisSentinelLister(indexer cache.Indexer) RedisSentinelLister {
	return &redisSentinelLister{listers.New[*gitopsv1alpha1.RedisSentinel](indexer, gitopsv1alpha1.Resource("redissentinel"))}
}

// RedisSentinels returns an object that can list and get RedisSentinels.
func (s *redisSentinelLister) RedisSentinels(namespace string) RedisSentinelNamespaceLister {
	return redisSentinelNamespaceLister{listers.NewNamespaced[*gitopsv1alpha1.RedisSentinel](s.ResourceIndexer, namespace)}
}

// RedisSentinelNamespaceLister helps list and get RedisSentinels.
// All objects returned here must be treated as read-only.
type RedisSentinelNamespaceLister interface {
	// List lists all RedisSentinels in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*gitopsv1alpha1.RedisSentinel, err error)
	// Get retrieves the RedisSentinel from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*gitopsv1alpha1.RedisSentinel, error)
	RedisSentinelNamespaceListerExpansion
}

// redisSentinelNamespaceLister implements the RedisSentinelNamespaceLister
// interface.
type redisSentinelNamespaceLister struct {
	listers.ResourceIndexer[*gitopsv1alpha1.RedisSentinel]
}
