/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHazelcastOpsRequests implements HazelcastOpsRequestInterface
type FakeHazelcastOpsRequests struct {
	Fake *FakeOpsV1alpha1
	ns   string
}

var hazelcastopsrequestsResource = v1alpha1.SchemeGroupVersion.WithResource("hazelcastopsrequests")

var hazelcastopsrequestsKind = v1alpha1.SchemeGroupVersion.WithKind("HazelcastOpsRequest")

// Get takes name of the hazelcastOpsRequest, and returns the corresponding hazelcastOpsRequest object, and an error if there is any.
func (c *FakeHazelcastOpsRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HazelcastOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hazelcastopsrequestsResource, c.ns, name), &v1alpha1.HazelcastOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HazelcastOpsRequest), err
}

// List takes label and field selectors, and returns the list of HazelcastOpsRequests that match those selectors.
func (c *FakeHazelcastOpsRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HazelcastOpsRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hazelcastopsrequestsResource, hazelcastopsrequestsKind, c.ns, opts), &v1alpha1.HazelcastOpsRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HazelcastOpsRequestList{ListMeta: obj.(*v1alpha1.HazelcastOpsRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.HazelcastOpsRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hazelcastOpsRequests.
func (c *FakeHazelcastOpsRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hazelcastopsrequestsResource, c.ns, opts))

}

// Create takes the representation of a hazelcastOpsRequest and creates it.  Returns the server's representation of the hazelcastOpsRequest, and an error, if there is any.
func (c *FakeHazelcastOpsRequests) Create(ctx context.Context, hazelcastOpsRequest *v1alpha1.HazelcastOpsRequest, opts v1.CreateOptions) (result *v1alpha1.HazelcastOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hazelcastopsrequestsResource, c.ns, hazelcastOpsRequest), &v1alpha1.HazelcastOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HazelcastOpsRequest), err
}

// Update takes the representation of a hazelcastOpsRequest and updates it. Returns the server's representation of the hazelcastOpsRequest, and an error, if there is any.
func (c *FakeHazelcastOpsRequests) Update(ctx context.Context, hazelcastOpsRequest *v1alpha1.HazelcastOpsRequest, opts v1.UpdateOptions) (result *v1alpha1.HazelcastOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hazelcastopsrequestsResource, c.ns, hazelcastOpsRequest), &v1alpha1.HazelcastOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HazelcastOpsRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHazelcastOpsRequests) UpdateStatus(ctx context.Context, hazelcastOpsRequest *v1alpha1.HazelcastOpsRequest, opts v1.UpdateOptions) (*v1alpha1.HazelcastOpsRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hazelcastopsrequestsResource, "status", c.ns, hazelcastOpsRequest), &v1alpha1.HazelcastOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HazelcastOpsRequest), err
}

// Delete takes name of the hazelcastOpsRequest and deletes it. Returns an error if one occurs.
func (c *FakeHazelcastOpsRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hazelcastopsrequestsResource, c.ns, name, opts), &v1alpha1.HazelcastOpsRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHazelcastOpsRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hazelcastopsrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HazelcastOpsRequestList{})
	return err
}

// Patch applies the patch and returns the patched hazelcastOpsRequest.
func (c *FakeHazelcastOpsRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HazelcastOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hazelcastopsrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HazelcastOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HazelcastOpsRequest), err
}
