/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMilvusOpsRequests implements MilvusOpsRequestInterface
type FakeMilvusOpsRequests struct {
	Fake *FakeOpsV1alpha1
	ns   string
}

var milvusopsrequestsResource = v1alpha1.SchemeGroupVersion.WithResource("milvusopsrequests")

var milvusopsrequestsKind = v1alpha1.SchemeGroupVersion.WithKind("MilvusOpsRequest")

// Get takes name of the milvusOpsRequest, and returns the corresponding milvusOpsRequest object, and an error if there is any.
func (c *FakeMilvusOpsRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MilvusOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(milvusopsrequestsResource, c.ns, name), &v1alpha1.MilvusOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusOpsRequest), err
}

// List takes label and field selectors, and returns the list of MilvusOpsRequests that match those selectors.
func (c *FakeMilvusOpsRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MilvusOpsRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(milvusopsrequestsResource, milvusopsrequestsKind, c.ns, opts), &v1alpha1.MilvusOpsRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MilvusOpsRequestList{ListMeta: obj.(*v1alpha1.MilvusOpsRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.MilvusOpsRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested milvusOpsRequests.
func (c *FakeMilvusOpsRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(milvusopsrequestsResource, c.ns, opts))

}

// Create takes the representation of a milvusOpsRequest and creates it.  Returns the server's representation of the milvusOpsRequest, and an error, if there is any.
func (c *FakeMilvusOpsRequests) Create(ctx context.Context, milvusOpsRequest *v1alpha1.MilvusOpsRequest, opts v1.CreateOptions) (result *v1alpha1.MilvusOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(milvusopsrequestsResource, c.ns, milvusOpsRequest), &v1alpha1.MilvusOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusOpsRequest), err
}

// Update takes the representation of a milvusOpsRequest and updates it. Returns the server's representation of the milvusOpsRequest, and an error, if there is any.
func (c *FakeMilvusOpsRequests) Update(ctx context.Context, milvusOpsRequest *v1alpha1.MilvusOpsRequest, opts v1.UpdateOptions) (result *v1alpha1.MilvusOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(milvusopsrequestsResource, c.ns, milvusOpsRequest), &v1alpha1.MilvusOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusOpsRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMilvusOpsRequests) UpdateStatus(ctx context.Context, milvusOpsRequest *v1alpha1.MilvusOpsRequest, opts v1.UpdateOptions) (*v1alpha1.MilvusOpsRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(milvusopsrequestsResource, "status", c.ns, milvusOpsRequest), &v1alpha1.MilvusOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusOpsRequest), err
}

// Delete takes name of the milvusOpsRequest and deletes it. Returns an error if one occurs.
func (c *FakeMilvusOpsRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(milvusopsrequestsResource, c.ns, name, opts), &v1alpha1.MilvusOpsRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMilvusOpsRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(milvusopsrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MilvusOpsRequestList{})
	return err
}

// Patch applies the patch and returns the patched milvusOpsRequest.
func (c *FakeMilvusOpsRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MilvusOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(milvusopsrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MilvusOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MilvusOpsRequest), err
}
