/*
Copyright The KubeDB Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePostgresOpsRequests implements PostgresOpsRequestInterface
type FakePostgresOpsRequests struct {
	Fake *FakeOpsV1alpha1
	ns   string
}

var postgresopsrequestsResource = schema.GroupVersionResource{Group: "ops.kubedb.com", Version: "v1alpha1", Resource: "postgresopsrequests"}

var postgresopsrequestsKind = schema.GroupVersionKind{Group: "ops.kubedb.com", Version: "v1alpha1", Kind: "PostgresOpsRequest"}

// Get takes name of the postgresOpsRequest, and returns the corresponding postgresOpsRequest object, and an error if there is any.
func (c *FakePostgresOpsRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PostgresOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(postgresopsrequestsResource, c.ns, name), &v1alpha1.PostgresOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PostgresOpsRequest), err
}

// List takes label and field selectors, and returns the list of PostgresOpsRequests that match those selectors.
func (c *FakePostgresOpsRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PostgresOpsRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(postgresopsrequestsResource, postgresopsrequestsKind, c.ns, opts), &v1alpha1.PostgresOpsRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PostgresOpsRequestList{ListMeta: obj.(*v1alpha1.PostgresOpsRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.PostgresOpsRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested postgresOpsRequests.
func (c *FakePostgresOpsRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(postgresopsrequestsResource, c.ns, opts))

}

// Create takes the representation of a postgresOpsRequest and creates it.  Returns the server's representation of the postgresOpsRequest, and an error, if there is any.
func (c *FakePostgresOpsRequests) Create(ctx context.Context, postgresOpsRequest *v1alpha1.PostgresOpsRequest, opts v1.CreateOptions) (result *v1alpha1.PostgresOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(postgresopsrequestsResource, c.ns, postgresOpsRequest), &v1alpha1.PostgresOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PostgresOpsRequest), err
}

// Update takes the representation of a postgresOpsRequest and updates it. Returns the server's representation of the postgresOpsRequest, and an error, if there is any.
func (c *FakePostgresOpsRequests) Update(ctx context.Context, postgresOpsRequest *v1alpha1.PostgresOpsRequest, opts v1.UpdateOptions) (result *v1alpha1.PostgresOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(postgresopsrequestsResource, c.ns, postgresOpsRequest), &v1alpha1.PostgresOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PostgresOpsRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePostgresOpsRequests) UpdateStatus(ctx context.Context, postgresOpsRequest *v1alpha1.PostgresOpsRequest, opts v1.UpdateOptions) (*v1alpha1.PostgresOpsRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(postgresopsrequestsResource, "status", c.ns, postgresOpsRequest), &v1alpha1.PostgresOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PostgresOpsRequest), err
}

// Delete takes name of the postgresOpsRequest and deletes it. Returns an error if one occurs.
func (c *FakePostgresOpsRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(postgresopsrequestsResource, c.ns, name), &v1alpha1.PostgresOpsRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePostgresOpsRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(postgresopsrequestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PostgresOpsRequestList{})
	return err
}

// Patch applies the patch and returns the patched postgresOpsRequest.
func (c *FakePostgresOpsRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PostgresOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(postgresopsrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PostgresOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PostgresOpsRequest), err
}
