/*
Copyright The KubeDB Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeElasticsearchOpsRequests implements ElasticsearchOpsRequestInterface
type FakeElasticsearchOpsRequests struct {
	Fake *FakeOpsV1alpha1
	ns   string
}

var elasticsearchopsrequestsResource = schema.GroupVersionResource{Group: "ops.kubedb.com", Version: "v1alpha1", Resource: "elasticsearchopsrequests"}

var elasticsearchopsrequestsKind = schema.GroupVersionKind{Group: "ops.kubedb.com", Version: "v1alpha1", Kind: "ElasticsearchOpsRequest"}

// Get takes name of the elasticsearchOpsRequest, and returns the corresponding elasticsearchOpsRequest object, and an error if there is any.
func (c *FakeElasticsearchOpsRequests) Get(name string, options v1.GetOptions) (result *v1alpha1.ElasticsearchOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(elasticsearchopsrequestsResource, c.ns, name), &v1alpha1.ElasticsearchOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchOpsRequest), err
}

// List takes label and field selectors, and returns the list of ElasticsearchOpsRequests that match those selectors.
func (c *FakeElasticsearchOpsRequests) List(opts v1.ListOptions) (result *v1alpha1.ElasticsearchOpsRequestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(elasticsearchopsrequestsResource, elasticsearchopsrequestsKind, c.ns, opts), &v1alpha1.ElasticsearchOpsRequestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ElasticsearchOpsRequestList{ListMeta: obj.(*v1alpha1.ElasticsearchOpsRequestList).ListMeta}
	for _, item := range obj.(*v1alpha1.ElasticsearchOpsRequestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested elasticsearchOpsRequests.
func (c *FakeElasticsearchOpsRequests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(elasticsearchopsrequestsResource, c.ns, opts))

}

// Create takes the representation of a elasticsearchOpsRequest and creates it.  Returns the server's representation of the elasticsearchOpsRequest, and an error, if there is any.
func (c *FakeElasticsearchOpsRequests) Create(elasticsearchOpsRequest *v1alpha1.ElasticsearchOpsRequest) (result *v1alpha1.ElasticsearchOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(elasticsearchopsrequestsResource, c.ns, elasticsearchOpsRequest), &v1alpha1.ElasticsearchOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchOpsRequest), err
}

// Update takes the representation of a elasticsearchOpsRequest and updates it. Returns the server's representation of the elasticsearchOpsRequest, and an error, if there is any.
func (c *FakeElasticsearchOpsRequests) Update(elasticsearchOpsRequest *v1alpha1.ElasticsearchOpsRequest) (result *v1alpha1.ElasticsearchOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(elasticsearchopsrequestsResource, c.ns, elasticsearchOpsRequest), &v1alpha1.ElasticsearchOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchOpsRequest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeElasticsearchOpsRequests) UpdateStatus(elasticsearchOpsRequest *v1alpha1.ElasticsearchOpsRequest) (*v1alpha1.ElasticsearchOpsRequest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(elasticsearchopsrequestsResource, "status", c.ns, elasticsearchOpsRequest), &v1alpha1.ElasticsearchOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchOpsRequest), err
}

// Delete takes name of the elasticsearchOpsRequest and deletes it. Returns an error if one occurs.
func (c *FakeElasticsearchOpsRequests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(elasticsearchopsrequestsResource, c.ns, name), &v1alpha1.ElasticsearchOpsRequest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeElasticsearchOpsRequests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(elasticsearchopsrequestsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ElasticsearchOpsRequestList{})
	return err
}

// Patch applies the patch and returns the patched elasticsearchOpsRequest.
func (c *FakeElasticsearchOpsRequests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ElasticsearchOpsRequest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(elasticsearchopsrequestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ElasticsearchOpsRequest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ElasticsearchOpsRequest), err
}
