/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kafkav1alpha1 "kubedb.dev/apimachinery/apis/kafka/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RestProxiesGetter has a method to return a RestProxyInterface.
// A group's client should implement this interface.
type RestProxiesGetter interface {
	RestProxies(namespace string) RestProxyInterface
}

// RestProxyInterface has methods to work with RestProxy resources.
type RestProxyInterface interface {
	Create(ctx context.Context, restProxy *kafkav1alpha1.RestProxy, opts v1.CreateOptions) (*kafkav1alpha1.RestProxy, error)
	Update(ctx context.Context, restProxy *kafkav1alpha1.RestProxy, opts v1.UpdateOptions) (*kafkav1alpha1.RestProxy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, restProxy *kafkav1alpha1.RestProxy, opts v1.UpdateOptions) (*kafkav1alpha1.RestProxy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kafkav1alpha1.RestProxy, error)
	List(ctx context.Context, opts v1.ListOptions) (*kafkav1alpha1.RestProxyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kafkav1alpha1.RestProxy, err error)
	RestProxyExpansion
}

// restProxies implements RestProxyInterface
type restProxies struct {
	*gentype.ClientWithList[*kafkav1alpha1.RestProxy, *kafkav1alpha1.RestProxyList]
}

// newRestProxies returns a RestProxies
func newRestProxies(c *KafkaV1alpha1Client, namespace string) *restProxies {
	return &restProxies{
		gentype.NewClientWithList[*kafkav1alpha1.RestProxy, *kafkav1alpha1.RestProxyList](
			"restproxies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkav1alpha1.RestProxy { return &kafkav1alpha1.RestProxy{} },
			func() *kafkav1alpha1.RestProxyList { return &kafkav1alpha1.RestProxyList{} },
		),
	}
}
