/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kafkav1alpha1 "kubedb.dev/apimachinery/apis/kafka/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SchemaRegistriesGetter has a method to return a SchemaRegistryInterface.
// A group's client should implement this interface.
type SchemaRegistriesGetter interface {
	SchemaRegistries(namespace string) SchemaRegistryInterface
}

// SchemaRegistryInterface has methods to work with SchemaRegistry resources.
type SchemaRegistryInterface interface {
	Create(ctx context.Context, schemaRegistry *kafkav1alpha1.SchemaRegistry, opts v1.CreateOptions) (*kafkav1alpha1.SchemaRegistry, error)
	Update(ctx context.Context, schemaRegistry *kafkav1alpha1.SchemaRegistry, opts v1.UpdateOptions) (*kafkav1alpha1.SchemaRegistry, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, schemaRegistry *kafkav1alpha1.SchemaRegistry, opts v1.UpdateOptions) (*kafkav1alpha1.SchemaRegistry, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kafkav1alpha1.SchemaRegistry, error)
	List(ctx context.Context, opts v1.ListOptions) (*kafkav1alpha1.SchemaRegistryList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kafkav1alpha1.SchemaRegistry, err error)
	SchemaRegistryExpansion
}

// schemaRegistries implements SchemaRegistryInterface
type schemaRegistries struct {
	*gentype.ClientWithList[*kafkav1alpha1.SchemaRegistry, *kafkav1alpha1.SchemaRegistryList]
}

// newSchemaRegistries returns a SchemaRegistries
func newSchemaRegistries(c *KafkaV1alpha1Client, namespace string) *schemaRegistries {
	return &schemaRegistries{
		gentype.NewClientWithList[*kafkav1alpha1.SchemaRegistry, *kafkav1alpha1.SchemaRegistryList](
			"schemaregistries",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kafkav1alpha1.SchemaRegistry { return &kafkav1alpha1.SchemaRegistry{} },
			func() *kafkav1alpha1.SchemaRegistryList { return &kafkav1alpha1.SchemaRegistryList{} },
		),
	}
}
