/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CassandraInsightLister helps list CassandraInsights.
// All objects returned here must be treated as read-only.
type CassandraInsightLister interface {
	// List lists all CassandraInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.CassandraInsight, err error)
	// CassandraInsights returns an object that can list and get CassandraInsights.
	CassandraInsights(namespace string) CassandraInsightNamespaceLister
	CassandraInsightListerExpansion
}

// cassandraInsightLister implements the CassandraInsightLister interface.
type cassandraInsightLister struct {
	listers.ResourceIndexer[*uiv1alpha1.CassandraInsight]
}

// NewCassandraInsightLister returns a new CassandraInsightLister.
func NewCassandraInsightLister(indexer cache.Indexer) CassandraInsightLister {
	return &cassandraInsightLister{listers.New[*uiv1alpha1.CassandraInsight](indexer, uiv1alpha1.Resource("cassandrainsight"))}
}

// CassandraInsights returns an object that can list and get CassandraInsights.
func (s *cassandraInsightLister) CassandraInsights(namespace string) CassandraInsightNamespaceLister {
	return cassandraInsightNamespaceLister{listers.NewNamespaced[*uiv1alpha1.CassandraInsight](s.ResourceIndexer, namespace)}
}

// CassandraInsightNamespaceLister helps list and get CassandraInsights.
// All objects returned here must be treated as read-only.
type CassandraInsightNamespaceLister interface {
	// List lists all CassandraInsights in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.CassandraInsight, err error)
	// Get retrieves the CassandraInsight from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*uiv1alpha1.CassandraInsight, error)
	CassandraInsightNamespaceListerExpansion
}

// cassandraInsightNamespaceLister implements the CassandraInsightNamespaceLister
// interface.
type cassandraInsightNamespaceLister struct {
	listers.ResourceIndexer[*uiv1alpha1.CassandraInsight]
}
