/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DB2SchemaOverviewLister helps list DB2SchemaOverviews.
// All objects returned here must be treated as read-only.
type DB2SchemaOverviewLister interface {
	// List lists all DB2SchemaOverviews in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.DB2SchemaOverview, err error)
	// DB2SchemaOverviews returns an object that can list and get DB2SchemaOverviews.
	DB2SchemaOverviews(namespace string) DB2SchemaOverviewNamespaceLister
	DB2SchemaOverviewListerExpansion
}

// dB2SchemaOverviewLister implements the DB2SchemaOverviewLister interface.
type dB2SchemaOverviewLister struct {
	listers.ResourceIndexer[*uiv1alpha1.DB2SchemaOverview]
}

// NewDB2SchemaOverviewLister returns a new DB2SchemaOverviewLister.
func NewDB2SchemaOverviewLister(indexer cache.Indexer) DB2SchemaOverviewLister {
	return &dB2SchemaOverviewLister{listers.New[*uiv1alpha1.DB2SchemaOverview](indexer, uiv1alpha1.Resource("db2schemaoverview"))}
}

// DB2SchemaOverviews returns an object that can list and get DB2SchemaOverviews.
func (s *dB2SchemaOverviewLister) DB2SchemaOverviews(namespace string) DB2SchemaOverviewNamespaceLister {
	return dB2SchemaOverviewNamespaceLister{listers.NewNamespaced[*uiv1alpha1.DB2SchemaOverview](s.ResourceIndexer, namespace)}
}

// DB2SchemaOverviewNamespaceLister helps list and get DB2SchemaOverviews.
// All objects returned here must be treated as read-only.
type DB2SchemaOverviewNamespaceLister interface {
	// List lists all DB2SchemaOverviews in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.DB2SchemaOverview, err error)
	// Get retrieves the DB2SchemaOverview from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*uiv1alpha1.DB2SchemaOverview, error)
	DB2SchemaOverviewNamespaceListerExpansion
}

// dB2SchemaOverviewNamespaceLister implements the DB2SchemaOverviewNamespaceLister
// interface.
type dB2SchemaOverviewNamespaceLister struct {
	listers.ResourceIndexer[*uiv1alpha1.DB2SchemaOverview]
}
