/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticsearchNodesStatsLister helps list ElasticsearchNodesStatses.
// All objects returned here must be treated as read-only.
type ElasticsearchNodesStatsLister interface {
	// List lists all ElasticsearchNodesStatses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.ElasticsearchNodesStats, err error)
	// ElasticsearchNodesStatses returns an object that can list and get ElasticsearchNodesStatses.
	ElasticsearchNodesStatses(namespace string) ElasticsearchNodesStatsNamespaceLister
	ElasticsearchNodesStatsListerExpansion
}

// elasticsearchNodesStatsLister implements the ElasticsearchNodesStatsLister interface.
type elasticsearchNodesStatsLister struct {
	listers.ResourceIndexer[*uiv1alpha1.ElasticsearchNodesStats]
}

// NewElasticsearchNodesStatsLister returns a new ElasticsearchNodesStatsLister.
func NewElasticsearchNodesStatsLister(indexer cache.Indexer) ElasticsearchNodesStatsLister {
	return &elasticsearchNodesStatsLister{listers.New[*uiv1alpha1.ElasticsearchNodesStats](indexer, uiv1alpha1.Resource("elasticsearchnodesstats"))}
}

// ElasticsearchNodesStatses returns an object that can list and get ElasticsearchNodesStatses.
func (s *elasticsearchNodesStatsLister) ElasticsearchNodesStatses(namespace string) ElasticsearchNodesStatsNamespaceLister {
	return elasticsearchNodesStatsNamespaceLister{listers.NewNamespaced[*uiv1alpha1.ElasticsearchNodesStats](s.ResourceIndexer, namespace)}
}

// ElasticsearchNodesStatsNamespaceLister helps list and get ElasticsearchNodesStatses.
// All objects returned here must be treated as read-only.
type ElasticsearchNodesStatsNamespaceLister interface {
	// List lists all ElasticsearchNodesStatses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.ElasticsearchNodesStats, err error)
	// Get retrieves the ElasticsearchNodesStats from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*uiv1alpha1.ElasticsearchNodesStats, error)
	ElasticsearchNodesStatsNamespaceListerExpansion
}

// elasticsearchNodesStatsNamespaceLister implements the ElasticsearchNodesStatsNamespaceLister
// interface.
type elasticsearchNodesStatsNamespaceLister struct {
	listers.ResourceIndexer[*uiv1alpha1.ElasticsearchNodesStats]
}
