/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// Neo4jInsightLister helps list Neo4jInsights.
// All objects returned here must be treated as read-only.
type Neo4jInsightLister interface {
	// List lists all Neo4jInsights in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.Neo4jInsight, err error)
	// Neo4jInsights returns an object that can list and get Neo4jInsights.
	Neo4jInsights(namespace string) Neo4jInsightNamespaceLister
	Neo4jInsightListerExpansion
}

// neo4jInsightLister implements the Neo4jInsightLister interface.
type neo4jInsightLister struct {
	listers.ResourceIndexer[*uiv1alpha1.Neo4jInsight]
}

// NewNeo4jInsightLister returns a new Neo4jInsightLister.
func NewNeo4jInsightLister(indexer cache.Indexer) Neo4jInsightLister {
	return &neo4jInsightLister{listers.New[*uiv1alpha1.Neo4jInsight](indexer, uiv1alpha1.Resource("neo4jinsight"))}
}

// Neo4jInsights returns an object that can list and get Neo4jInsights.
func (s *neo4jInsightLister) Neo4jInsights(namespace string) Neo4jInsightNamespaceLister {
	return neo4jInsightNamespaceLister{listers.NewNamespaced[*uiv1alpha1.Neo4jInsight](s.ResourceIndexer, namespace)}
}

// Neo4jInsightNamespaceLister helps list and get Neo4jInsights.
// All objects returned here must be treated as read-only.
type Neo4jInsightNamespaceLister interface {
	// List lists all Neo4jInsights in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*uiv1alpha1.Neo4jInsight, err error)
	// Get retrieves the Neo4jInsight from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*uiv1alpha1.Neo4jInsight, error)
	Neo4jInsightNamespaceListerExpansion
}

// neo4jInsightNamespaceLister implements the Neo4jInsightNamespaceLister
// interface.
type neo4jInsightNamespaceLister struct {
	listers.ResourceIndexer[*uiv1alpha1.Neo4jInsight]
}
