/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
)

// FakeMsSQLs implements MsSQLInterface
type FakeMsSQLs struct {
	Fake *FakeKubedbV1alpha2
	ns   string
}

var mssqlsResource = v1alpha2.SchemeGroupVersion.WithResource("mssqls")

var mssqlsKind = v1alpha2.SchemeGroupVersion.WithKind("MsSQL")

// Get takes name of the msSQL, and returns the corresponding msSQL object, and an error if there is any.
func (c *FakeMsSQLs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.MsSQL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mssqlsResource, c.ns, name), &v1alpha2.MsSQL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MsSQL), err
}

// List takes label and field selectors, and returns the list of MsSQLs that match those selectors.
func (c *FakeMsSQLs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.MsSQLList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mssqlsResource, mssqlsKind, c.ns, opts), &v1alpha2.MsSQLList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.MsSQLList{ListMeta: obj.(*v1alpha2.MsSQLList).ListMeta}
	for _, item := range obj.(*v1alpha2.MsSQLList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested msSQLs.
func (c *FakeMsSQLs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mssqlsResource, c.ns, opts))

}

// Create takes the representation of a msSQL and creates it.  Returns the server's representation of the msSQL, and an error, if there is any.
func (c *FakeMsSQLs) Create(ctx context.Context, msSQL *v1alpha2.MsSQL, opts v1.CreateOptions) (result *v1alpha2.MsSQL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mssqlsResource, c.ns, msSQL), &v1alpha2.MsSQL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MsSQL), err
}

// Update takes the representation of a msSQL and updates it. Returns the server's representation of the msSQL, and an error, if there is any.
func (c *FakeMsSQLs) Update(ctx context.Context, msSQL *v1alpha2.MsSQL, opts v1.UpdateOptions) (result *v1alpha2.MsSQL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mssqlsResource, c.ns, msSQL), &v1alpha2.MsSQL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MsSQL), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMsSQLs) UpdateStatus(ctx context.Context, msSQL *v1alpha2.MsSQL, opts v1.UpdateOptions) (*v1alpha2.MsSQL, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mssqlsResource, "status", c.ns, msSQL), &v1alpha2.MsSQL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MsSQL), err
}

// Delete takes name of the msSQL and deletes it. Returns an error if one occurs.
func (c *FakeMsSQLs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mssqlsResource, c.ns, name, opts), &v1alpha2.MsSQL{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMsSQLs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mssqlsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.MsSQLList{})
	return err
}

// Patch applies the patch and returns the patched msSQL.
func (c *FakeMsSQLs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.MsSQL, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mssqlsResource, c.ns, name, pt, data, subresources...), &v1alpha2.MsSQL{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.MsSQL), err
}
