/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
)

// FakeDB2s implements DB2Interface
type FakeDB2s struct {
	Fake *FakeKubedbV1alpha2
	ns   string
}

var db2sResource = v1alpha2.SchemeGroupVersion.WithResource("db2s")

var db2sKind = v1alpha2.SchemeGroupVersion.WithKind("DB2")

// Get takes name of the dB2, and returns the corresponding dB2 object, and an error if there is any.
func (c *FakeDB2s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.DB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(db2sResource, c.ns, name), &v1alpha2.DB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DB2), err
}

// List takes label and field selectors, and returns the list of DB2s that match those selectors.
func (c *FakeDB2s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.DB2List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(db2sResource, db2sKind, c.ns, opts), &v1alpha2.DB2List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.DB2List{ListMeta: obj.(*v1alpha2.DB2List).ListMeta}
	for _, item := range obj.(*v1alpha2.DB2List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dB2s.
func (c *FakeDB2s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(db2sResource, c.ns, opts))

}

// Create takes the representation of a dB2 and creates it.  Returns the server's representation of the dB2, and an error, if there is any.
func (c *FakeDB2s) Create(ctx context.Context, dB2 *v1alpha2.DB2, opts v1.CreateOptions) (result *v1alpha2.DB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(db2sResource, c.ns, dB2), &v1alpha2.DB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DB2), err
}

// Update takes the representation of a dB2 and updates it. Returns the server's representation of the dB2, and an error, if there is any.
func (c *FakeDB2s) Update(ctx context.Context, dB2 *v1alpha2.DB2, opts v1.UpdateOptions) (result *v1alpha2.DB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(db2sResource, c.ns, dB2), &v1alpha2.DB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DB2), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDB2s) UpdateStatus(ctx context.Context, dB2 *v1alpha2.DB2, opts v1.UpdateOptions) (*v1alpha2.DB2, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(db2sResource, "status", c.ns, dB2), &v1alpha2.DB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DB2), err
}

// Delete takes name of the dB2 and deletes it. Returns an error if one occurs.
func (c *FakeDB2s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(db2sResource, c.ns, name, opts), &v1alpha2.DB2{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDB2s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(db2sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.DB2List{})
	return err
}

// Patch applies the patch and returns the patched dB2.
func (c *FakeDB2s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.DB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(db2sResource, c.ns, name, pt, data, subresources...), &v1alpha2.DB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.DB2), err
}
