/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKafkas implements KafkaInterface
type FakeKafkas struct {
	Fake *FakeKubedbV1alpha2
	ns   string
}

var kafkasResource = schema.GroupVersionResource{Group: "kubedb.com", Version: "v1alpha2", Resource: "kafkas"}

var kafkasKind = schema.GroupVersionKind{Group: "kubedb.com", Version: "v1alpha2", Kind: "Kafka"}

// Get takes name of the kafka, and returns the corresponding kafka object, and an error if there is any.
func (c *FakeKafkas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.Kafka, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kafkasResource, c.ns, name), &v1alpha2.Kafka{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kafka), err
}

// List takes label and field selectors, and returns the list of Kafkas that match those selectors.
func (c *FakeKafkas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.KafkaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kafkasResource, kafkasKind, c.ns, opts), &v1alpha2.KafkaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.KafkaList{ListMeta: obj.(*v1alpha2.KafkaList).ListMeta}
	for _, item := range obj.(*v1alpha2.KafkaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kafkas.
func (c *FakeKafkas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kafkasResource, c.ns, opts))

}

// Create takes the representation of a kafka and creates it.  Returns the server's representation of the kafka, and an error, if there is any.
func (c *FakeKafkas) Create(ctx context.Context, kafka *v1alpha2.Kafka, opts v1.CreateOptions) (result *v1alpha2.Kafka, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kafkasResource, c.ns, kafka), &v1alpha2.Kafka{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kafka), err
}

// Update takes the representation of a kafka and updates it. Returns the server's representation of the kafka, and an error, if there is any.
func (c *FakeKafkas) Update(ctx context.Context, kafka *v1alpha2.Kafka, opts v1.UpdateOptions) (result *v1alpha2.Kafka, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kafkasResource, c.ns, kafka), &v1alpha2.Kafka{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kafka), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKafkas) UpdateStatus(ctx context.Context, kafka *v1alpha2.Kafka, opts v1.UpdateOptions) (*v1alpha2.Kafka, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kafkasResource, "status", c.ns, kafka), &v1alpha2.Kafka{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kafka), err
}

// Delete takes name of the kafka and deletes it. Returns an error if one occurs.
func (c *FakeKafkas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kafkasResource, c.ns, name, opts), &v1alpha2.Kafka{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKafkas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kafkasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.KafkaList{})
	return err
}

// Patch applies the patch and returns the patched kafka.
func (c *FakeKafkas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.Kafka, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kafkasResource, c.ns, name, pt, data, subresources...), &v1alpha2.Kafka{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Kafka), err
}
