/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSinglestores implements SinglestoreInterface
type FakeSinglestores struct {
	Fake *FakeKubedbV1alpha2
	ns   string
}

var singlestoresResource = v1alpha2.SchemeGroupVersion.WithResource("singlestores")

var singlestoresKind = v1alpha2.SchemeGroupVersion.WithKind("Singlestore")

// Get takes name of the singlestore, and returns the corresponding singlestore object, and an error if there is any.
func (c *FakeSinglestores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.Singlestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(singlestoresResource, c.ns, name), &v1alpha2.Singlestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Singlestore), err
}

// List takes label and field selectors, and returns the list of Singlestores that match those selectors.
func (c *FakeSinglestores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.SinglestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(singlestoresResource, singlestoresKind, c.ns, opts), &v1alpha2.SinglestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.SinglestoreList{ListMeta: obj.(*v1alpha2.SinglestoreList).ListMeta}
	for _, item := range obj.(*v1alpha2.SinglestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested singlestores.
func (c *FakeSinglestores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(singlestoresResource, c.ns, opts))

}

// Create takes the representation of a singlestore and creates it.  Returns the server's representation of the singlestore, and an error, if there is any.
func (c *FakeSinglestores) Create(ctx context.Context, singlestore *v1alpha2.Singlestore, opts v1.CreateOptions) (result *v1alpha2.Singlestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(singlestoresResource, c.ns, singlestore), &v1alpha2.Singlestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Singlestore), err
}

// Update takes the representation of a singlestore and updates it. Returns the server's representation of the singlestore, and an error, if there is any.
func (c *FakeSinglestores) Update(ctx context.Context, singlestore *v1alpha2.Singlestore, opts v1.UpdateOptions) (result *v1alpha2.Singlestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(singlestoresResource, c.ns, singlestore), &v1alpha2.Singlestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Singlestore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSinglestores) UpdateStatus(ctx context.Context, singlestore *v1alpha2.Singlestore, opts v1.UpdateOptions) (*v1alpha2.Singlestore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(singlestoresResource, "status", c.ns, singlestore), &v1alpha2.Singlestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Singlestore), err
}

// Delete takes name of the singlestore and deletes it. Returns an error if one occurs.
func (c *FakeSinglestores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(singlestoresResource, c.ns, name, opts), &v1alpha2.Singlestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSinglestores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(singlestoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.SinglestoreList{})
	return err
}

// Patch applies the patch and returns the patched singlestore.
func (c *FakeSinglestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.Singlestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(singlestoresResource, c.ns, name, pt, data, subresources...), &v1alpha2.Singlestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Singlestore), err
}
