/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
)

// FakeMySQLAutoscalers implements MySQLAutoscalerInterface
type FakeMySQLAutoscalers struct {
	Fake *FakeAutoscalingV1alpha1
	ns   string
}

var mysqlautoscalersResource = schema.GroupVersionResource{Group: "autoscaling.kubedb.com", Version: "v1alpha1", Resource: "mysqlautoscalers"}

var mysqlautoscalersKind = schema.GroupVersionKind{Group: "autoscaling.kubedb.com", Version: "v1alpha1", Kind: "MySQLAutoscaler"}

// Get takes name of the mySQLAutoscaler, and returns the corresponding mySQLAutoscaler object, and an error if there is any.
func (c *FakeMySQLAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MySQLAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mysqlautoscalersResource, c.ns, name), &v1alpha1.MySQLAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLAutoscaler), err
}

// List takes label and field selectors, and returns the list of MySQLAutoscalers that match those selectors.
func (c *FakeMySQLAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MySQLAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mysqlautoscalersResource, mysqlautoscalersKind, c.ns, opts), &v1alpha1.MySQLAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MySQLAutoscalerList{ListMeta: obj.(*v1alpha1.MySQLAutoscalerList).ListMeta}
	for _, item := range obj.(*v1alpha1.MySQLAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mySQLAutoscalers.
func (c *FakeMySQLAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mysqlautoscalersResource, c.ns, opts))

}

// Create takes the representation of a mySQLAutoscaler and creates it.  Returns the server's representation of the mySQLAutoscaler, and an error, if there is any.
func (c *FakeMySQLAutoscalers) Create(ctx context.Context, mySQLAutoscaler *v1alpha1.MySQLAutoscaler, opts v1.CreateOptions) (result *v1alpha1.MySQLAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mysqlautoscalersResource, c.ns, mySQLAutoscaler), &v1alpha1.MySQLAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLAutoscaler), err
}

// Update takes the representation of a mySQLAutoscaler and updates it. Returns the server's representation of the mySQLAutoscaler, and an error, if there is any.
func (c *FakeMySQLAutoscalers) Update(ctx context.Context, mySQLAutoscaler *v1alpha1.MySQLAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.MySQLAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mysqlautoscalersResource, c.ns, mySQLAutoscaler), &v1alpha1.MySQLAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMySQLAutoscalers) UpdateStatus(ctx context.Context, mySQLAutoscaler *v1alpha1.MySQLAutoscaler, opts v1.UpdateOptions) (*v1alpha1.MySQLAutoscaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mysqlautoscalersResource, "status", c.ns, mySQLAutoscaler), &v1alpha1.MySQLAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLAutoscaler), err
}

// Delete takes name of the mySQLAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeMySQLAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mysqlautoscalersResource, c.ns, name), &v1alpha1.MySQLAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMySQLAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mysqlautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MySQLAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched mySQLAutoscaler.
func (c *FakeMySQLAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MySQLAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mysqlautoscalersResource, c.ns, name, pt, data, subresources...), &v1alpha1.MySQLAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MySQLAutoscaler), err
}
