/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
	autoscalingv1alpha1 "kubedb.dev/apimachinery/client/clientset/versioned/typed/autoscaling/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeNeo4jAutoscalers implements Neo4jAutoscalerInterface
type fakeNeo4jAutoscalers struct {
	*gentype.FakeClientWithList[*v1alpha1.Neo4jAutoscaler, *v1alpha1.Neo4jAutoscalerList]
	Fake *FakeAutoscalingV1alpha1
}

func newFakeNeo4jAutoscalers(fake *FakeAutoscalingV1alpha1, namespace string) autoscalingv1alpha1.Neo4jAutoscalerInterface {
	return &fakeNeo4jAutoscalers{
		gentype.NewFakeClientWithList[*v1alpha1.Neo4jAutoscaler, *v1alpha1.Neo4jAutoscalerList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("neo4jautoscalers"),
			v1alpha1.SchemeGroupVersion.WithKind("Neo4jAutoscaler"),
			func() *v1alpha1.Neo4jAutoscaler { return &v1alpha1.Neo4jAutoscaler{} },
			func() *v1alpha1.Neo4jAutoscalerList { return &v1alpha1.Neo4jAutoscalerList{} },
			func(dst, src *v1alpha1.Neo4jAutoscalerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.Neo4jAutoscalerList) []*v1alpha1.Neo4jAutoscaler {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.Neo4jAutoscalerList, items []*v1alpha1.Neo4jAutoscaler) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
