/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DatabaseConnectionsGetter has a method to return a DatabaseConnectionInterface.
// A group's client should implement this interface.
type DatabaseConnectionsGetter interface {
	DatabaseConnections(namespace string) DatabaseConnectionInterface
}

// DatabaseConnectionInterface has methods to work with DatabaseConnection resources.
type DatabaseConnectionInterface interface {
	Create(ctx context.Context, databaseConnection *uiv1alpha1.DatabaseConnection, opts v1.CreateOptions) (*uiv1alpha1.DatabaseConnection, error)
	Update(ctx context.Context, databaseConnection *uiv1alpha1.DatabaseConnection, opts v1.UpdateOptions) (*uiv1alpha1.DatabaseConnection, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, databaseConnection *uiv1alpha1.DatabaseConnection, opts v1.UpdateOptions) (*uiv1alpha1.DatabaseConnection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*uiv1alpha1.DatabaseConnection, error)
	List(ctx context.Context, opts v1.ListOptions) (*uiv1alpha1.DatabaseConnectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *uiv1alpha1.DatabaseConnection, err error)
	DatabaseConnectionExpansion
}

// databaseConnections implements DatabaseConnectionInterface
type databaseConnections struct {
	*gentype.ClientWithList[*uiv1alpha1.DatabaseConnection, *uiv1alpha1.DatabaseConnectionList]
}

// newDatabaseConnections returns a DatabaseConnections
func newDatabaseConnections(c *UiV1alpha1Client, namespace string) *databaseConnections {
	return &databaseConnections{
		gentype.NewClientWithList[*uiv1alpha1.DatabaseConnection, *uiv1alpha1.DatabaseConnectionList](
			"databaseconnections",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *uiv1alpha1.DatabaseConnection { return &uiv1alpha1.DatabaseConnection{} },
			func() *uiv1alpha1.DatabaseConnectionList { return &uiv1alpha1.DatabaseConnectionList{} },
		),
	}
}
