/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	uiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MilvusSchemaOverviewsGetter has a method to return a MilvusSchemaOverviewInterface.
// A group's client should implement this interface.
type MilvusSchemaOverviewsGetter interface {
	MilvusSchemaOverviews(namespace string) MilvusSchemaOverviewInterface
}

// MilvusSchemaOverviewInterface has methods to work with MilvusSchemaOverview resources.
type MilvusSchemaOverviewInterface interface {
	Create(ctx context.Context, milvusSchemaOverview *uiv1alpha1.MilvusSchemaOverview, opts v1.CreateOptions) (*uiv1alpha1.MilvusSchemaOverview, error)
	Update(ctx context.Context, milvusSchemaOverview *uiv1alpha1.MilvusSchemaOverview, opts v1.UpdateOptions) (*uiv1alpha1.MilvusSchemaOverview, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*uiv1alpha1.MilvusSchemaOverview, error)
	List(ctx context.Context, opts v1.ListOptions) (*uiv1alpha1.MilvusSchemaOverviewList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *uiv1alpha1.MilvusSchemaOverview, err error)
	MilvusSchemaOverviewExpansion
}

// milvusSchemaOverviews implements MilvusSchemaOverviewInterface
type milvusSchemaOverviews struct {
	*gentype.ClientWithList[*uiv1alpha1.MilvusSchemaOverview, *uiv1alpha1.MilvusSchemaOverviewList]
}

// newMilvusSchemaOverviews returns a MilvusSchemaOverviews
func newMilvusSchemaOverviews(c *UiV1alpha1Client, namespace string) *milvusSchemaOverviews {
	return &milvusSchemaOverviews{
		gentype.NewClientWithList[*uiv1alpha1.MilvusSchemaOverview, *uiv1alpha1.MilvusSchemaOverviewList](
			"milvusschemaoverviews",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *uiv1alpha1.MilvusSchemaOverview { return &uiv1alpha1.MilvusSchemaOverview{} },
			func() *uiv1alpha1.MilvusSchemaOverviewList { return &uiv1alpha1.MilvusSchemaOverviewList{} },
		),
	}
}
