apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: verticalpodautopilotcheckpoints.autoscaling.kubedb.com
spec:
  group: autoscaling.kubedb.com
  names:
    kind: VerticalPodAutopilotCheckpoint
    listKind: VerticalPodAutopilotCheckpointList
    plural: verticalpodautopilotcheckpoints
    shortNames:
    - vpacheckpoint
    singular: verticalpodautopilotcheckpoint
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              containerName:
                type: string
              vpaObjectName:
                type: string
            type: object
          status:
            properties:
              cpuHistogram:
                properties:
                  bucketWeights:
                    items:
                      properties:
                        index:
                          type: integer
                        weight:
                          format: int32
                          type: integer
                      required:
                      - index
                      - weight
                      type: object
                    type: array
                    x-kubernetes-preserve-unknown-fields: true
                  referenceTimestamp:
                    format: date-time
                    nullable: true
                    type: string
                  totalWeight:
                    format: double
                    type: number
                type: object
              firstSampleStart:
                format: date-time
                nullable: true
                type: string
              lastSampleStart:
                format: date-time
                nullable: true
                type: string
              lastUpdateTime:
                format: date-time
                nullable: true
                type: string
              memoryHistogram:
                properties:
                  bucketWeights:
                    items:
                      properties:
                        index:
                          type: integer
                        weight:
                          format: int32
                          type: integer
                      required:
                      - index
                      - weight
                      type: object
                    type: array
                    x-kubernetes-preserve-unknown-fields: true
                  referenceTimestamp:
                    format: date-time
                    nullable: true
                    type: string
                  totalWeight:
                    format: double
                    type: number
                type: object
              totalSamplesCount:
                type: integer
              version:
                type: string
            type: object
        type: object
    served: true
    storage: true
