
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: db2Hadrs.kubedb.com
spec:
  group: kubedb.com
  names:
    categories:
    - datastore
    - kubedb
    - appscode
    - all
    kind: DB2Hadr
    listKind: DB2HadrList
    plural: db2Hadrs
    shortNames:
    - db2Hadr
    singular: db2Hadr
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .apiVersion
      name: Type
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha2
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              configSecret:
                properties:
                  activeFrom:
                    format: date-time
                    type: string
                  apiGroup:
                    default: ""
                    type: string
                  externallyManaged:
                    type: boolean
                  kind:
                    default: Secret
                    type: string
                  name:
                    type: string
                  rotateAfter:
                    type: string
                  secretStoreName:
                    type: string
                required:
                - kind
                - name
                type: object
                x-kubernetes-map-type: atomic
              primary:
                properties:
                  id:
                    format: int64
                    type: integer
                type: object
              serviceTemplates:
                items:
                  properties:
                    alias:
                      enum:
                      - primary
                      - standby
                      - stats
                      - dashboard
                      - secondary
                      type: string
                    metadata:
                      properties:
                        annotations:
                          additionalProperties:
                            type: string
                          type: object
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    spec:
                      properties:
                        clusterIP:
                          type: string
                        externalIPs:
                          items:
                            type: string
                          type: array
                        externalTrafficPolicy:
                          type: string
                        healthCheckNodePort:
                          format: int32
                          type: integer
                        loadBalancerIP:
                          type: string
                        loadBalancerSourceRanges:
                          items:
                            type: string
                          type: array
                        ports:
                          items:
                            properties:
                              name:
                                type: string
                              nodePort:
                                format: int32
                                type: integer
                              port:
                                format: int32
                                type: integer
                            required:
                            - port
                            type: object
                          type: array
                        sessionAffinityConfig:
                          properties:
                            clientIP:
                              properties:
                                timeoutSeconds:
                                  format: int32
                                  type: integer
                              type: object
                          type: object
                        type:
                          type: string
                      type: object
                  required:
                  - alias
                  type: object
                type: array
              standby:
                properties:
                  id:
                    format: int64
                    type: integer
                type: object
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
              phase:
                enum:
                - Provisioning
                - DataRestoring
                - Ready
                - Critical
                - NotReady
                - Halted
                - Unknown
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
