apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: migratoraddons.operator.kubedb.com
spec:
  group: operator.kubedb.com
  names:
    categories:
    - kubedb
    - appscode
    - all
    kind: MigratorAddon
    listKind: MigratorAddonList
    plural: migratoraddons
    shortNames:
    - mgaddon
    singular: migratoraddon
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              imagePullPolicy:
                default: IfNotPresent
                enum:
                - Always
                - IfNotPresent
                - Never
                type: string
              imagePullSecrets:
                items:
                  type: string
                type: array
              migratorImages:
                properties:
                  mariadb:
                    type: string
                  mongodb:
                    type: string
                  mssqlserver:
                    type: string
                  mysql:
                    type: string
                  postgres:
                    type: string
                  sidecar:
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
