apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: proxysqlsettings.ui.kubedb.com
spec:
  group: ui.kubedb.com
  names:
    kind: ProxySQLSettings
    listKind: ProxySQLSettingsList
    plural: proxysqlsettings
    singular: proxysqlsettings
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              settings:
                items:
                  properties:
                    currentValue:
                      type: string
                    defaultValue:
                      type: string
                    name:
                      type: string
                    source:
                      type: string
                    unit:
                      type: string
                  required:
                  - currentValue
                  - defaultValue
                  - name
                  type: object
                type: array
            required:
            - settings
            type: object
        type: object
    served: true
    storage: true
