apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: neo4jnodesstats.ui.kubedb.com
spec:
  group: ui.kubedb.com
  names:
    kind: Neo4jNodesStats
    listKind: Neo4jNodesStatsList
    plural: neo4jnodesstats
    singular: neo4jnodesstats
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              collectedAt:
                format: date-time
                type: string
              databases:
                items:
                  properties:
                    access:
                      type: string
                    address:
                      type: string
                    currentStatus:
                      type: string
                    databaseID:
                      type: string
                    default:
                      type: boolean
                    home:
                      type: boolean
                    name:
                      type: string
                    requestedStatus:
                      type: string
                    role:
                      type: string
                    serverID:
                      type: string
                    statusMessage:
                      type: string
                    type:
                      type: string
                    writer:
                      type: boolean
                  required:
                  - name
                  type: object
                type: array
              servers:
                items:
                  properties:
                    address:
                      type: string
                    health:
                      type: string
                    hosting:
                      items:
                        type: string
                      type: array
                    modeConstraint:
                      type: string
                    name:
                      type: string
                    requestedHosting:
                      items:
                        type: string
                      type: array
                    serverID:
                      type: string
                    state:
                      type: string
                    version:
                      type: string
                  required:
                  - health
                  - name
                  - state
                  type: object
                type: array
            required:
            - databases
            - servers
            type: object
        type: object
    served: true
    storage: true
