apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubedb
  name: elasticsearchinsights.ui.kubedb.com
spec:
  group: ui.kubedb.com
  names:
    kind: ElasticsearchInsight
    listKind: ElasticsearchInsightList
    plural: elasticsearchinsights
    singular: elasticsearchinsight
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              clusterHealth:
                properties:
                  activePrimaryShards:
                    format: int32
                    type: integer
                  activeShards:
                    format: int32
                    type: integer
                  activeShardsPercentAsNumber:
                    format: int32
                    type: integer
                  clusterName:
                    type: string
                  delayedUnassignedShards:
                    format: int32
                    type: integer
                  initializingShards:
                    format: int32
                    type: integer
                  numberOfDataNodes:
                    format: int32
                    type: integer
                  numberOfInFlightFetch:
                    format: int32
                    type: integer
                  numberOfNodes:
                    format: int32
                    type: integer
                  numberOfPendingTasks:
                    format: int32
                    type: integer
                  relocatingShards:
                    format: int32
                    type: integer
                  status:
                    type: string
                  taskMaxWaitingInQueueMilliSeconds:
                    format: int32
                    type: integer
                  unassignedShards:
                    format: int32
                    type: integer
                required:
                - activePrimaryShards
                - activeShards
                - activeShardsPercentAsNumber
                - clusterName
                - delayedUnassignedShards
                - initializingShards
                - numberOfDataNodes
                - numberOfInFlightFetch
                - numberOfNodes
                - numberOfPendingTasks
                - relocatingShards
                - status
                - taskMaxWaitingInQueueMilliSeconds
                - unassignedShards
                type: object
              mode:
                type: string
              status:
                type: string
              version:
                type: string
            required:
            - mode
            - status
            - version
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
              phase:
                enum:
                - Provisioning
                - DataRestoring
                - Ready
                - Critical
                - NotReady
                - Halted
                type: string
            type: object
        type: object
    served: true
    storage: true
