/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubedbv1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EtcdsGetter has a method to return a EtcdInterface.
// A group's client should implement this interface.
type EtcdsGetter interface {
	Etcds(namespace string) EtcdInterface
}

// EtcdInterface has methods to work with Etcd resources.
type EtcdInterface interface {
	Create(ctx context.Context, etcd *kubedbv1alpha2.Etcd, opts v1.CreateOptions) (*kubedbv1alpha2.Etcd, error)
	Update(ctx context.Context, etcd *kubedbv1alpha2.Etcd, opts v1.UpdateOptions) (*kubedbv1alpha2.Etcd, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, etcd *kubedbv1alpha2.Etcd, opts v1.UpdateOptions) (*kubedbv1alpha2.Etcd, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubedbv1alpha2.Etcd, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubedbv1alpha2.EtcdList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubedbv1alpha2.Etcd, err error)
	EtcdExpansion
}

// etcds implements EtcdInterface
type etcds struct {
	*gentype.ClientWithList[*kubedbv1alpha2.Etcd, *kubedbv1alpha2.EtcdList]
}

// newEtcds returns a Etcds
func newEtcds(c *KubedbV1alpha2Client, namespace string) *etcds {
	return &etcds{
		gentype.NewClientWithList[*kubedbv1alpha2.Etcd, *kubedbv1alpha2.EtcdList](
			"etcds",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubedbv1alpha2.Etcd { return &kubedbv1alpha2.Etcd{} },
			func() *kubedbv1alpha2.EtcdList { return &kubedbv1alpha2.EtcdList{} },
		),
	}
}
