/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubedbv1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProxySQLsGetter has a method to return a ProxySQLInterface.
// A group's client should implement this interface.
type ProxySQLsGetter interface {
	ProxySQLs(namespace string) ProxySQLInterface
}

// ProxySQLInterface has methods to work with ProxySQL resources.
type ProxySQLInterface interface {
	Create(ctx context.Context, proxySQL *kubedbv1alpha2.ProxySQL, opts v1.CreateOptions) (*kubedbv1alpha2.ProxySQL, error)
	Update(ctx context.Context, proxySQL *kubedbv1alpha2.ProxySQL, opts v1.UpdateOptions) (*kubedbv1alpha2.ProxySQL, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, proxySQL *kubedbv1alpha2.ProxySQL, opts v1.UpdateOptions) (*kubedbv1alpha2.ProxySQL, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubedbv1alpha2.ProxySQL, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubedbv1alpha2.ProxySQLList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubedbv1alpha2.ProxySQL, err error)
	ProxySQLExpansion
}

// proxySQLs implements ProxySQLInterface
type proxySQLs struct {
	*gentype.ClientWithList[*kubedbv1alpha2.ProxySQL, *kubedbv1alpha2.ProxySQLList]
}

// newProxySQLs returns a ProxySQLs
func newProxySQLs(c *KubedbV1alpha2Client, namespace string) *proxySQLs {
	return &proxySQLs{
		gentype.NewClientWithList[*kubedbv1alpha2.ProxySQL, *kubedbv1alpha2.ProxySQLList](
			"proxysqls",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubedbv1alpha2.ProxySQL { return &kubedbv1alpha2.ProxySQL{} },
			func() *kubedbv1alpha2.ProxySQLList { return &kubedbv1alpha2.ProxySQLList{} },
		),
	}
}
