/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubedbv1alpha2 "kubedb.dev/apimachinery/apis/kubedb/v1alpha2"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SinglestoresGetter has a method to return a SinglestoreInterface.
// A group's client should implement this interface.
type SinglestoresGetter interface {
	Singlestores(namespace string) SinglestoreInterface
}

// SinglestoreInterface has methods to work with Singlestore resources.
type SinglestoreInterface interface {
	Create(ctx context.Context, singlestore *kubedbv1alpha2.Singlestore, opts v1.CreateOptions) (*kubedbv1alpha2.Singlestore, error)
	Update(ctx context.Context, singlestore *kubedbv1alpha2.Singlestore, opts v1.UpdateOptions) (*kubedbv1alpha2.Singlestore, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, singlestore *kubedbv1alpha2.Singlestore, opts v1.UpdateOptions) (*kubedbv1alpha2.Singlestore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubedbv1alpha2.Singlestore, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubedbv1alpha2.SinglestoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubedbv1alpha2.Singlestore, err error)
	SinglestoreExpansion
}

// singlestores implements SinglestoreInterface
type singlestores struct {
	*gentype.ClientWithList[*kubedbv1alpha2.Singlestore, *kubedbv1alpha2.SinglestoreList]
}

// newSinglestores returns a Singlestores
func newSinglestores(c *KubedbV1alpha2Client, namespace string) *singlestores {
	return &singlestores{
		gentype.NewClientWithList[*kubedbv1alpha2.Singlestore, *kubedbv1alpha2.SinglestoreList](
			"singlestores",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubedbv1alpha2.Singlestore { return &kubedbv1alpha2.Singlestore{} },
			func() *kubedbv1alpha2.SinglestoreList { return &kubedbv1alpha2.SinglestoreList{} },
		),
	}
}
