/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DB2OpsRequestLister helps list DB2OpsRequests.
// All objects returned here must be treated as read-only.
type DB2OpsRequestLister interface {
	// List lists all DB2OpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.DB2OpsRequest, err error)
	// DB2OpsRequests returns an object that can list and get DB2OpsRequests.
	DB2OpsRequests(namespace string) DB2OpsRequestNamespaceLister
	DB2OpsRequestListerExpansion
}

// dB2OpsRequestLister implements the DB2OpsRequestLister interface.
type dB2OpsRequestLister struct {
	listers.ResourceIndexer[*opsv1alpha1.DB2OpsRequest]
}

// NewDB2OpsRequestLister returns a new DB2OpsRequestLister.
func NewDB2OpsRequestLister(indexer cache.Indexer) DB2OpsRequestLister {
	return &dB2OpsRequestLister{listers.New[*opsv1alpha1.DB2OpsRequest](indexer, opsv1alpha1.Resource("db2opsrequest"))}
}

// DB2OpsRequests returns an object that can list and get DB2OpsRequests.
func (s *dB2OpsRequestLister) DB2OpsRequests(namespace string) DB2OpsRequestNamespaceLister {
	return dB2OpsRequestNamespaceLister{listers.NewNamespaced[*opsv1alpha1.DB2OpsRequest](s.ResourceIndexer, namespace)}
}

// DB2OpsRequestNamespaceLister helps list and get DB2OpsRequests.
// All objects returned here must be treated as read-only.
type DB2OpsRequestNamespaceLister interface {
	// List lists all DB2OpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.DB2OpsRequest, err error)
	// Get retrieves the DB2OpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*opsv1alpha1.DB2OpsRequest, error)
	DB2OpsRequestNamespaceListerExpansion
}

// dB2OpsRequestNamespaceLister implements the DB2OpsRequestNamespaceLister
// interface.
type dB2OpsRequestNamespaceLister struct {
	listers.ResourceIndexer[*opsv1alpha1.DB2OpsRequest]
}
