/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HanaDBOpsRequestLister helps list HanaDBOpsRequests.
// All objects returned here must be treated as read-only.
type HanaDBOpsRequestLister interface {
	// List lists all HanaDBOpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HanaDBOpsRequest, err error)
	// HanaDBOpsRequests returns an object that can list and get HanaDBOpsRequests.
	HanaDBOpsRequests(namespace string) HanaDBOpsRequestNamespaceLister
	HanaDBOpsRequestListerExpansion
}

// hanaDBOpsRequestLister implements the HanaDBOpsRequestLister interface.
type hanaDBOpsRequestLister struct {
	indexer cache.Indexer
}

// NewHanaDBOpsRequestLister returns a new HanaDBOpsRequestLister.
func NewHanaDBOpsRequestLister(indexer cache.Indexer) HanaDBOpsRequestLister {
	return &hanaDBOpsRequestLister{indexer: indexer}
}

// List lists all HanaDBOpsRequests in the indexer.
func (s *hanaDBOpsRequestLister) List(selector labels.Selector) (ret []*v1alpha1.HanaDBOpsRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HanaDBOpsRequest))
	})
	return ret, err
}

// HanaDBOpsRequests returns an object that can list and get HanaDBOpsRequests.
func (s *hanaDBOpsRequestLister) HanaDBOpsRequests(namespace string) HanaDBOpsRequestNamespaceLister {
	return hanaDBOpsRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HanaDBOpsRequestNamespaceLister helps list and get HanaDBOpsRequests.
// All objects returned here must be treated as read-only.
type HanaDBOpsRequestNamespaceLister interface {
	// List lists all HanaDBOpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HanaDBOpsRequest, err error)
	// Get retrieves the HanaDBOpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HanaDBOpsRequest, error)
	HanaDBOpsRequestNamespaceListerExpansion
}

// hanaDBOpsRequestNamespaceLister implements the HanaDBOpsRequestNamespaceLister
// interface.
type hanaDBOpsRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HanaDBOpsRequests in the indexer for a given namespace.
func (s hanaDBOpsRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HanaDBOpsRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HanaDBOpsRequest))
	})
	return ret, err
}

// Get retrieves the HanaDBOpsRequest from the indexer for a given namespace and name.
func (s hanaDBOpsRequestNamespaceLister) Get(name string) (*v1alpha1.HanaDBOpsRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hanadbopsrequest"), name)
	}
	return obj.(*v1alpha1.HanaDBOpsRequest), nil
}
