/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MilvusOpsRequestLister helps list MilvusOpsRequests.
// All objects returned here must be treated as read-only.
type MilvusOpsRequestLister interface {
	// List lists all MilvusOpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusOpsRequest, err error)
	// MilvusOpsRequests returns an object that can list and get MilvusOpsRequests.
	MilvusOpsRequests(namespace string) MilvusOpsRequestNamespaceLister
	MilvusOpsRequestListerExpansion
}

// milvusOpsRequestLister implements the MilvusOpsRequestLister interface.
type milvusOpsRequestLister struct {
	indexer cache.Indexer
}

// NewMilvusOpsRequestLister returns a new MilvusOpsRequestLister.
func NewMilvusOpsRequestLister(indexer cache.Indexer) MilvusOpsRequestLister {
	return &milvusOpsRequestLister{indexer: indexer}
}

// List lists all MilvusOpsRequests in the indexer.
func (s *milvusOpsRequestLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusOpsRequest, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusOpsRequest))
	})
	return ret, err
}

// MilvusOpsRequests returns an object that can list and get MilvusOpsRequests.
func (s *milvusOpsRequestLister) MilvusOpsRequests(namespace string) MilvusOpsRequestNamespaceLister {
	return milvusOpsRequestNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MilvusOpsRequestNamespaceLister helps list and get MilvusOpsRequests.
// All objects returned here must be treated as read-only.
type MilvusOpsRequestNamespaceLister interface {
	// List lists all MilvusOpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusOpsRequest, err error)
	// Get retrieves the MilvusOpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MilvusOpsRequest, error)
	MilvusOpsRequestNamespaceListerExpansion
}

// milvusOpsRequestNamespaceLister implements the MilvusOpsRequestNamespaceLister
// interface.
type milvusOpsRequestNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MilvusOpsRequests in the indexer for a given namespace.
func (s milvusOpsRequestNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusOpsRequest, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusOpsRequest))
	})
	return ret, err
}

// Get retrieves the MilvusOpsRequest from the indexer for a given namespace and name.
func (s milvusOpsRequestNamespaceLister) Get(name string) (*v1alpha1.MilvusOpsRequest, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("milvusopsrequest"), name)
	}
	return obj.(*v1alpha1.MilvusOpsRequest), nil
}
