/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MongoDBOpsRequestLister helps list MongoDBOpsRequests.
// All objects returned here must be treated as read-only.
type MongoDBOpsRequestLister interface {
	// List lists all MongoDBOpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.MongoDBOpsRequest, err error)
	// MongoDBOpsRequests returns an object that can list and get MongoDBOpsRequests.
	MongoDBOpsRequests(namespace string) MongoDBOpsRequestNamespaceLister
	MongoDBOpsRequestListerExpansion
}

// mongoDBOpsRequestLister implements the MongoDBOpsRequestLister interface.
type mongoDBOpsRequestLister struct {
	listers.ResourceIndexer[*opsv1alpha1.MongoDBOpsRequest]
}

// NewMongoDBOpsRequestLister returns a new MongoDBOpsRequestLister.
func NewMongoDBOpsRequestLister(indexer cache.Indexer) MongoDBOpsRequestLister {
	return &mongoDBOpsRequestLister{listers.New[*opsv1alpha1.MongoDBOpsRequest](indexer, opsv1alpha1.Resource("mongodbopsrequest"))}
}

// MongoDBOpsRequests returns an object that can list and get MongoDBOpsRequests.
func (s *mongoDBOpsRequestLister) MongoDBOpsRequests(namespace string) MongoDBOpsRequestNamespaceLister {
	return mongoDBOpsRequestNamespaceLister{listers.NewNamespaced[*opsv1alpha1.MongoDBOpsRequest](s.ResourceIndexer, namespace)}
}

// MongoDBOpsRequestNamespaceLister helps list and get MongoDBOpsRequests.
// All objects returned here must be treated as read-only.
type MongoDBOpsRequestNamespaceLister interface {
	// List lists all MongoDBOpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.MongoDBOpsRequest, err error)
	// Get retrieves the MongoDBOpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*opsv1alpha1.MongoDBOpsRequest, error)
	MongoDBOpsRequestNamespaceListerExpansion
}

// mongoDBOpsRequestNamespaceLister implements the MongoDBOpsRequestNamespaceLister
// interface.
type mongoDBOpsRequestNamespaceLister struct {
	listers.ResourceIndexer[*opsv1alpha1.MongoDBOpsRequest]
}
