/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WeaviateOpsRequestLister helps list WeaviateOpsRequests.
// All objects returned here must be treated as read-only.
type WeaviateOpsRequestLister interface {
	// List lists all WeaviateOpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.WeaviateOpsRequest, err error)
	// WeaviateOpsRequests returns an object that can list and get WeaviateOpsRequests.
	WeaviateOpsRequests(namespace string) WeaviateOpsRequestNamespaceLister
	WeaviateOpsRequestListerExpansion
}

// weaviateOpsRequestLister implements the WeaviateOpsRequestLister interface.
type weaviateOpsRequestLister struct {
	listers.ResourceIndexer[*opsv1alpha1.WeaviateOpsRequest]
}

// NewWeaviateOpsRequestLister returns a new WeaviateOpsRequestLister.
func NewWeaviateOpsRequestLister(indexer cache.Indexer) WeaviateOpsRequestLister {
	return &weaviateOpsRequestLister{listers.New[*opsv1alpha1.WeaviateOpsRequest](indexer, opsv1alpha1.Resource("weaviateopsrequest"))}
}

// WeaviateOpsRequests returns an object that can list and get WeaviateOpsRequests.
func (s *weaviateOpsRequestLister) WeaviateOpsRequests(namespace string) WeaviateOpsRequestNamespaceLister {
	return weaviateOpsRequestNamespaceLister{listers.NewNamespaced[*opsv1alpha1.WeaviateOpsRequest](s.ResourceIndexer, namespace)}
}

// WeaviateOpsRequestNamespaceLister helps list and get WeaviateOpsRequests.
// All objects returned here must be treated as read-only.
type WeaviateOpsRequestNamespaceLister interface {
	// List lists all WeaviateOpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.WeaviateOpsRequest, err error)
	// Get retrieves the WeaviateOpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*opsv1alpha1.WeaviateOpsRequest, error)
	WeaviateOpsRequestNamespaceListerExpansion
}

// weaviateOpsRequestNamespaceLister implements the WeaviateOpsRequestNamespaceLister
// interface.
type weaviateOpsRequestNamespaceLister struct {
	listers.ResourceIndexer[*opsv1alpha1.WeaviateOpsRequest]
}
