/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClickHouseAutoscalersGetter has a method to return a ClickHouseAutoscalerInterface.
// A group's client should implement this interface.
type ClickHouseAutoscalersGetter interface {
	ClickHouseAutoscalers(namespace string) ClickHouseAutoscalerInterface
}

// ClickHouseAutoscalerInterface has methods to work with ClickHouseAutoscaler resources.
type ClickHouseAutoscalerInterface interface {
	Create(ctx context.Context, clickHouseAutoscaler *autoscalingv1alpha1.ClickHouseAutoscaler, opts v1.CreateOptions) (*autoscalingv1alpha1.ClickHouseAutoscaler, error)
	Update(ctx context.Context, clickHouseAutoscaler *autoscalingv1alpha1.ClickHouseAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.ClickHouseAutoscaler, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clickHouseAutoscaler *autoscalingv1alpha1.ClickHouseAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.ClickHouseAutoscaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingv1alpha1.ClickHouseAutoscaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingv1alpha1.ClickHouseAutoscalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingv1alpha1.ClickHouseAutoscaler, err error)
	ClickHouseAutoscalerExpansion
}

// clickHouseAutoscalers implements ClickHouseAutoscalerInterface
type clickHouseAutoscalers struct {
	*gentype.ClientWithList[*autoscalingv1alpha1.ClickHouseAutoscaler, *autoscalingv1alpha1.ClickHouseAutoscalerList]
}

// newClickHouseAutoscalers returns a ClickHouseAutoscalers
func newClickHouseAutoscalers(c *AutoscalingV1alpha1Client, namespace string) *clickHouseAutoscalers {
	return &clickHouseAutoscalers{
		gentype.NewClientWithList[*autoscalingv1alpha1.ClickHouseAutoscaler, *autoscalingv1alpha1.ClickHouseAutoscalerList](
			"clickhouseautoscalers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *autoscalingv1alpha1.ClickHouseAutoscaler { return &autoscalingv1alpha1.ClickHouseAutoscaler{} },
			func() *autoscalingv1alpha1.ClickHouseAutoscalerList {
				return &autoscalingv1alpha1.ClickHouseAutoscalerList{}
			},
		),
	}
}
