/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HazelcastAutoscalersGetter has a method to return a HazelcastAutoscalerInterface.
// A group's client should implement this interface.
type HazelcastAutoscalersGetter interface {
	HazelcastAutoscalers(namespace string) HazelcastAutoscalerInterface
}

// HazelcastAutoscalerInterface has methods to work with HazelcastAutoscaler resources.
type HazelcastAutoscalerInterface interface {
	Create(ctx context.Context, hazelcastAutoscaler *autoscalingv1alpha1.HazelcastAutoscaler, opts v1.CreateOptions) (*autoscalingv1alpha1.HazelcastAutoscaler, error)
	Update(ctx context.Context, hazelcastAutoscaler *autoscalingv1alpha1.HazelcastAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.HazelcastAutoscaler, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hazelcastAutoscaler *autoscalingv1alpha1.HazelcastAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.HazelcastAutoscaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingv1alpha1.HazelcastAutoscaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingv1alpha1.HazelcastAutoscalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingv1alpha1.HazelcastAutoscaler, err error)
	HazelcastAutoscalerExpansion
}

// hazelcastAutoscalers implements HazelcastAutoscalerInterface
type hazelcastAutoscalers struct {
	*gentype.ClientWithList[*autoscalingv1alpha1.HazelcastAutoscaler, *autoscalingv1alpha1.HazelcastAutoscalerList]
}

// newHazelcastAutoscalers returns a HazelcastAutoscalers
func newHazelcastAutoscalers(c *AutoscalingV1alpha1Client, namespace string) *hazelcastAutoscalers {
	return &hazelcastAutoscalers{
		gentype.NewClientWithList[*autoscalingv1alpha1.HazelcastAutoscaler, *autoscalingv1alpha1.HazelcastAutoscalerList](
			"hazelcastautoscalers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *autoscalingv1alpha1.HazelcastAutoscaler { return &autoscalingv1alpha1.HazelcastAutoscaler{} },
			func() *autoscalingv1alpha1.HazelcastAutoscalerList {
				return &autoscalingv1alpha1.HazelcastAutoscalerList{}
			},
		),
	}
}
