/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	autoscalingv1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// MySQLAutoscalersGetter has a method to return a MySQLAutoscalerInterface.
// A group's client should implement this interface.
type MySQLAutoscalersGetter interface {
	MySQLAutoscalers(namespace string) MySQLAutoscalerInterface
}

// MySQLAutoscalerInterface has methods to work with MySQLAutoscaler resources.
type MySQLAutoscalerInterface interface {
	Create(ctx context.Context, mySQLAutoscaler *autoscalingv1alpha1.MySQLAutoscaler, opts v1.CreateOptions) (*autoscalingv1alpha1.MySQLAutoscaler, error)
	Update(ctx context.Context, mySQLAutoscaler *autoscalingv1alpha1.MySQLAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.MySQLAutoscaler, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, mySQLAutoscaler *autoscalingv1alpha1.MySQLAutoscaler, opts v1.UpdateOptions) (*autoscalingv1alpha1.MySQLAutoscaler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*autoscalingv1alpha1.MySQLAutoscaler, error)
	List(ctx context.Context, opts v1.ListOptions) (*autoscalingv1alpha1.MySQLAutoscalerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *autoscalingv1alpha1.MySQLAutoscaler, err error)
	MySQLAutoscalerExpansion
}

// mySQLAutoscalers implements MySQLAutoscalerInterface
type mySQLAutoscalers struct {
	*gentype.ClientWithList[*autoscalingv1alpha1.MySQLAutoscaler, *autoscalingv1alpha1.MySQLAutoscalerList]
}

// newMySQLAutoscalers returns a MySQLAutoscalers
func newMySQLAutoscalers(c *AutoscalingV1alpha1Client, namespace string) *mySQLAutoscalers {
	return &mySQLAutoscalers{
		gentype.NewClientWithList[*autoscalingv1alpha1.MySQLAutoscaler, *autoscalingv1alpha1.MySQLAutoscalerList](
			"mysqlautoscalers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *autoscalingv1alpha1.MySQLAutoscaler { return &autoscalingv1alpha1.MySQLAutoscaler{} },
			func() *autoscalingv1alpha1.MySQLAutoscalerList { return &autoscalingv1alpha1.MySQLAutoscalerList{} },
		),
	}
}
