/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubedb.dev/apimachinery/apis/autoscaling/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerticalPodAutopilotsGetter has a method to return a VerticalPodAutopilotInterface.
// A group's client should implement this interface.
type VerticalPodAutopilotsGetter interface {
	VerticalPodAutopilots(namespace string) VerticalPodAutopilotInterface
}

// VerticalPodAutopilotInterface has methods to work with VerticalPodAutopilot resources.
type VerticalPodAutopilotInterface interface {
	Create(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.CreateOptions) (*v1alpha1.VerticalPodAutopilot, error)
	Update(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.UpdateOptions) (*v1alpha1.VerticalPodAutopilot, error)
	UpdateStatus(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.UpdateOptions) (*v1alpha1.VerticalPodAutopilot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VerticalPodAutopilot, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VerticalPodAutopilotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerticalPodAutopilot, err error)
	VerticalPodAutopilotExpansion
}

// verticalPodAutopilots implements VerticalPodAutopilotInterface
type verticalPodAutopilots struct {
	client rest.Interface
	ns     string
}

// newVerticalPodAutopilots returns a VerticalPodAutopilots
func newVerticalPodAutopilots(c *AutoscalingV1alpha1Client, namespace string) *verticalPodAutopilots {
	return &verticalPodAutopilots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the verticalPodAutopilot, and returns the corresponding verticalPodAutopilot object, and an error if there is any.
func (c *verticalPodAutopilots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VerticalPodAutopilot, err error) {
	result = &v1alpha1.VerticalPodAutopilot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VerticalPodAutopilots that match those selectors.
func (c *verticalPodAutopilots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VerticalPodAutopilotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VerticalPodAutopilotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested verticalPodAutopilots.
func (c *verticalPodAutopilots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a verticalPodAutopilot and creates it.  Returns the server's representation of the verticalPodAutopilot, and an error, if there is any.
func (c *verticalPodAutopilots) Create(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.CreateOptions) (result *v1alpha1.VerticalPodAutopilot, err error) {
	result = &v1alpha1.VerticalPodAutopilot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verticalPodAutopilot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a verticalPodAutopilot and updates it. Returns the server's representation of the verticalPodAutopilot, and an error, if there is any.
func (c *verticalPodAutopilots) Update(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.UpdateOptions) (result *v1alpha1.VerticalPodAutopilot, err error) {
	result = &v1alpha1.VerticalPodAutopilot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		Name(verticalPodAutopilot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verticalPodAutopilot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *verticalPodAutopilots) UpdateStatus(ctx context.Context, verticalPodAutopilot *v1alpha1.VerticalPodAutopilot, opts v1.UpdateOptions) (result *v1alpha1.VerticalPodAutopilot, err error) {
	result = &v1alpha1.VerticalPodAutopilot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		Name(verticalPodAutopilot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(verticalPodAutopilot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the verticalPodAutopilot and deletes it. Returns an error if one occurs.
func (c *verticalPodAutopilots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *verticalPodAutopilots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched verticalPodAutopilot.
func (c *verticalPodAutopilots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VerticalPodAutopilot, err error) {
	result = &v1alpha1.VerticalPodAutopilot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("verticalpodautopilots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
