// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package v1alpha1

import (
	"fmt"
	"strings"
)

const (
	// WeaviateOpsRequestTypeUpdateVersion is a WeaviateOpsRequestType of type UpdateVersion.
	WeaviateOpsRequestTypeUpdateVersion WeaviateOpsRequestType = "UpdateVersion"
	// WeaviateOpsRequestTypeHorizontalScaling is a WeaviateOpsRequestType of type HorizontalScaling.
	WeaviateOpsRequestTypeHorizontalScaling WeaviateOpsRequestType = "HorizontalScaling"
	// WeaviateOpsRequestTypeVerticalScaling is a WeaviateOpsRequestType of type VerticalScaling.
	WeaviateOpsRequestTypeVerticalScaling WeaviateOpsRequestType = "VerticalScaling"
	// WeaviateOpsRequestTypeVolumeExpansion is a WeaviateOpsRequestType of type VolumeExpansion.
	WeaviateOpsRequestTypeVolumeExpansion WeaviateOpsRequestType = "VolumeExpansion"
	// WeaviateOpsRequestTypeReconfigure is a WeaviateOpsRequestType of type Reconfigure.
	WeaviateOpsRequestTypeReconfigure WeaviateOpsRequestType = "Reconfigure"
	// WeaviateOpsRequestTypeRestart is a WeaviateOpsRequestType of type Restart.
	WeaviateOpsRequestTypeRestart WeaviateOpsRequestType = "Restart"
	// WeaviateOpsRequestTypeReconfigureTLS is a WeaviateOpsRequestType of type ReconfigureTLS.
	WeaviateOpsRequestTypeReconfigureTLS WeaviateOpsRequestType = "ReconfigureTLS"
	// WeaviateOpsRequestTypeRotateAuth is a WeaviateOpsRequestType of type RotateAuth.
	WeaviateOpsRequestTypeRotateAuth WeaviateOpsRequestType = "RotateAuth"
)

var ErrInvalidWeaviateOpsRequestType = fmt.Errorf("not a valid WeaviateOpsRequestType, try [%s]", strings.Join(_WeaviateOpsRequestTypeNames, ", "))

var _WeaviateOpsRequestTypeNames = []string{
	string(WeaviateOpsRequestTypeUpdateVersion),
	string(WeaviateOpsRequestTypeHorizontalScaling),
	string(WeaviateOpsRequestTypeVerticalScaling),
	string(WeaviateOpsRequestTypeVolumeExpansion),
	string(WeaviateOpsRequestTypeReconfigure),
	string(WeaviateOpsRequestTypeRestart),
	string(WeaviateOpsRequestTypeReconfigureTLS),
	string(WeaviateOpsRequestTypeRotateAuth),
}

// WeaviateOpsRequestTypeNames returns a list of possible string values of WeaviateOpsRequestType.
func WeaviateOpsRequestTypeNames() []string {
	tmp := make([]string, len(_WeaviateOpsRequestTypeNames))
	copy(tmp, _WeaviateOpsRequestTypeNames)
	return tmp
}

// WeaviateOpsRequestTypeValues returns a list of the values for WeaviateOpsRequestType
func WeaviateOpsRequestTypeValues() []WeaviateOpsRequestType {
	return []WeaviateOpsRequestType{
		WeaviateOpsRequestTypeUpdateVersion,
		WeaviateOpsRequestTypeHorizontalScaling,
		WeaviateOpsRequestTypeVerticalScaling,
		WeaviateOpsRequestTypeVolumeExpansion,
		WeaviateOpsRequestTypeReconfigure,
		WeaviateOpsRequestTypeRestart,
		WeaviateOpsRequestTypeReconfigureTLS,
		WeaviateOpsRequestTypeRotateAuth,
	}
}

// String implements the Stringer interface.
func (x WeaviateOpsRequestType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WeaviateOpsRequestType) IsValid() bool {
	_, err := ParseWeaviateOpsRequestType(string(x))
	return err == nil
}

var _WeaviateOpsRequestTypeValue = map[string]WeaviateOpsRequestType{
	"UpdateVersion":     WeaviateOpsRequestTypeUpdateVersion,
	"HorizontalScaling": WeaviateOpsRequestTypeHorizontalScaling,
	"VerticalScaling":   WeaviateOpsRequestTypeVerticalScaling,
	"VolumeExpansion":   WeaviateOpsRequestTypeVolumeExpansion,
	"Reconfigure":       WeaviateOpsRequestTypeReconfigure,
	"Restart":           WeaviateOpsRequestTypeRestart,
	"ReconfigureTLS":    WeaviateOpsRequestTypeReconfigureTLS,
	"RotateAuth":        WeaviateOpsRequestTypeRotateAuth,
}

// ParseWeaviateOpsRequestType attempts to convert a string to a WeaviateOpsRequestType.
func ParseWeaviateOpsRequestType(name string) (WeaviateOpsRequestType, error) {
	if x, ok := _WeaviateOpsRequestTypeValue[name]; ok {
		return x, nil
	}
	return WeaviateOpsRequestType(""), fmt.Errorf("%s is %w", name, ErrInvalidWeaviateOpsRequestType)
}

// MustParseWeaviateOpsRequestType converts a string to a WeaviateOpsRequestType, and panics if is not valid.
func MustParseWeaviateOpsRequestType(name string) WeaviateOpsRequestType {
	val, err := ParseWeaviateOpsRequestType(name)
	if err != nil {
		panic(err)
	}
	return val
}
