/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	schemav1alpha1 "kubedb.dev/apimachinery/apis/schema/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PostgresDatabasesGetter has a method to return a PostgresDatabaseInterface.
// A group's client should implement this interface.
type PostgresDatabasesGetter interface {
	PostgresDatabases(namespace string) PostgresDatabaseInterface
}

// PostgresDatabaseInterface has methods to work with PostgresDatabase resources.
type PostgresDatabaseInterface interface {
	Create(ctx context.Context, postgresDatabase *schemav1alpha1.PostgresDatabase, opts v1.CreateOptions) (*schemav1alpha1.PostgresDatabase, error)
	Update(ctx context.Context, postgresDatabase *schemav1alpha1.PostgresDatabase, opts v1.UpdateOptions) (*schemav1alpha1.PostgresDatabase, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, postgresDatabase *schemav1alpha1.PostgresDatabase, opts v1.UpdateOptions) (*schemav1alpha1.PostgresDatabase, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schemav1alpha1.PostgresDatabase, error)
	List(ctx context.Context, opts v1.ListOptions) (*schemav1alpha1.PostgresDatabaseList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schemav1alpha1.PostgresDatabase, err error)
	PostgresDatabaseExpansion
}

// postgresDatabases implements PostgresDatabaseInterface
type postgresDatabases struct {
	*gentype.ClientWithList[*schemav1alpha1.PostgresDatabase, *schemav1alpha1.PostgresDatabaseList]
}

// newPostgresDatabases returns a PostgresDatabases
func newPostgresDatabases(c *SchemaV1alpha1Client, namespace string) *postgresDatabases {
	return &postgresDatabases{
		gentype.NewClientWithList[*schemav1alpha1.PostgresDatabase, *schemav1alpha1.PostgresDatabaseList](
			"postgresdatabases",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schemav1alpha1.PostgresDatabase { return &schemav1alpha1.PostgresDatabase{} },
			func() *schemav1alpha1.PostgresDatabaseList { return &schemav1alpha1.PostgresDatabaseList{} },
		),
	}
}
