/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubedb.dev/apimachinery/apis/kafka/v1alpha1"
)

// FakeSchemaRegistries implements SchemaRegistryInterface
type FakeSchemaRegistries struct {
	Fake *FakeKafkaV1alpha1
	ns   string
}

var schemaregistriesResource = v1alpha1.SchemeGroupVersion.WithResource("schemaregistries")

var schemaregistriesKind = v1alpha1.SchemeGroupVersion.WithKind("SchemaRegistry")

// Get takes name of the schemaRegistry, and returns the corresponding schemaRegistry object, and an error if there is any.
func (c *FakeSchemaRegistries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SchemaRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(schemaregistriesResource, c.ns, name), &v1alpha1.SchemaRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaRegistry), err
}

// List takes label and field selectors, and returns the list of SchemaRegistries that match those selectors.
func (c *FakeSchemaRegistries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SchemaRegistryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(schemaregistriesResource, schemaregistriesKind, c.ns, opts), &v1alpha1.SchemaRegistryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SchemaRegistryList{ListMeta: obj.(*v1alpha1.SchemaRegistryList).ListMeta}
	for _, item := range obj.(*v1alpha1.SchemaRegistryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested schemaRegistries.
func (c *FakeSchemaRegistries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(schemaregistriesResource, c.ns, opts))

}

// Create takes the representation of a schemaRegistry and creates it.  Returns the server's representation of the schemaRegistry, and an error, if there is any.
func (c *FakeSchemaRegistries) Create(ctx context.Context, schemaRegistry *v1alpha1.SchemaRegistry, opts v1.CreateOptions) (result *v1alpha1.SchemaRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(schemaregistriesResource, c.ns, schemaRegistry), &v1alpha1.SchemaRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaRegistry), err
}

// Update takes the representation of a schemaRegistry and updates it. Returns the server's representation of the schemaRegistry, and an error, if there is any.
func (c *FakeSchemaRegistries) Update(ctx context.Context, schemaRegistry *v1alpha1.SchemaRegistry, opts v1.UpdateOptions) (result *v1alpha1.SchemaRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(schemaregistriesResource, c.ns, schemaRegistry), &v1alpha1.SchemaRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaRegistry), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSchemaRegistries) UpdateStatus(ctx context.Context, schemaRegistry *v1alpha1.SchemaRegistry, opts v1.UpdateOptions) (*v1alpha1.SchemaRegistry, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(schemaregistriesResource, "status", c.ns, schemaRegistry), &v1alpha1.SchemaRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaRegistry), err
}

// Delete takes name of the schemaRegistry and deletes it. Returns an error if one occurs.
func (c *FakeSchemaRegistries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(schemaregistriesResource, c.ns, name, opts), &v1alpha1.SchemaRegistry{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSchemaRegistries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(schemaregistriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SchemaRegistryList{})
	return err
}

// Patch applies the patch and returns the patched schemaRegistry.
func (c *FakeSchemaRegistries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SchemaRegistry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schemaregistriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SchemaRegistry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchemaRegistry), err
}
