/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DruidOpsRequestsGetter has a method to return a DruidOpsRequestInterface.
// A group's client should implement this interface.
type DruidOpsRequestsGetter interface {
	DruidOpsRequests(namespace string) DruidOpsRequestInterface
}

// DruidOpsRequestInterface has methods to work with DruidOpsRequest resources.
type DruidOpsRequestInterface interface {
	Create(ctx context.Context, druidOpsRequest *opsv1alpha1.DruidOpsRequest, opts v1.CreateOptions) (*opsv1alpha1.DruidOpsRequest, error)
	Update(ctx context.Context, druidOpsRequest *opsv1alpha1.DruidOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.DruidOpsRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, druidOpsRequest *opsv1alpha1.DruidOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.DruidOpsRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*opsv1alpha1.DruidOpsRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*opsv1alpha1.DruidOpsRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *opsv1alpha1.DruidOpsRequest, err error)
	DruidOpsRequestExpansion
}

// druidOpsRequests implements DruidOpsRequestInterface
type druidOpsRequests struct {
	*gentype.ClientWithList[*opsv1alpha1.DruidOpsRequest, *opsv1alpha1.DruidOpsRequestList]
}

// newDruidOpsRequests returns a DruidOpsRequests
func newDruidOpsRequests(c *OpsV1alpha1Client, namespace string) *druidOpsRequests {
	return &druidOpsRequests{
		gentype.NewClientWithList[*opsv1alpha1.DruidOpsRequest, *opsv1alpha1.DruidOpsRequestList](
			"druidopsrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *opsv1alpha1.DruidOpsRequest { return &opsv1alpha1.DruidOpsRequest{} },
			func() *opsv1alpha1.DruidOpsRequestList { return &opsv1alpha1.DruidOpsRequestList{} },
		),
	}
}
