/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HazelcastOpsRequestsGetter has a method to return a HazelcastOpsRequestInterface.
// A group's client should implement this interface.
type HazelcastOpsRequestsGetter interface {
	HazelcastOpsRequests(namespace string) HazelcastOpsRequestInterface
}

// HazelcastOpsRequestInterface has methods to work with HazelcastOpsRequest resources.
type HazelcastOpsRequestInterface interface {
	Create(ctx context.Context, hazelcastOpsRequest *opsv1alpha1.HazelcastOpsRequest, opts v1.CreateOptions) (*opsv1alpha1.HazelcastOpsRequest, error)
	Update(ctx context.Context, hazelcastOpsRequest *opsv1alpha1.HazelcastOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.HazelcastOpsRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hazelcastOpsRequest *opsv1alpha1.HazelcastOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.HazelcastOpsRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*opsv1alpha1.HazelcastOpsRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*opsv1alpha1.HazelcastOpsRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *opsv1alpha1.HazelcastOpsRequest, err error)
	HazelcastOpsRequestExpansion
}

// hazelcastOpsRequests implements HazelcastOpsRequestInterface
type hazelcastOpsRequests struct {
	*gentype.ClientWithList[*opsv1alpha1.HazelcastOpsRequest, *opsv1alpha1.HazelcastOpsRequestList]
}

// newHazelcastOpsRequests returns a HazelcastOpsRequests
func newHazelcastOpsRequests(c *OpsV1alpha1Client, namespace string) *hazelcastOpsRequests {
	return &hazelcastOpsRequests{
		gentype.NewClientWithList[*opsv1alpha1.HazelcastOpsRequest, *opsv1alpha1.HazelcastOpsRequestList](
			"hazelcastopsrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *opsv1alpha1.HazelcastOpsRequest { return &opsv1alpha1.HazelcastOpsRequest{} },
			func() *opsv1alpha1.HazelcastOpsRequestList { return &opsv1alpha1.HazelcastOpsRequestList{} },
		),
	}
}
