/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	opsv1alpha1 "kubedb.dev/apimachinery/apis/ops/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RabbitMQOpsRequestsGetter has a method to return a RabbitMQOpsRequestInterface.
// A group's client should implement this interface.
type RabbitMQOpsRequestsGetter interface {
	RabbitMQOpsRequests(namespace string) RabbitMQOpsRequestInterface
}

// RabbitMQOpsRequestInterface has methods to work with RabbitMQOpsRequest resources.
type RabbitMQOpsRequestInterface interface {
	Create(ctx context.Context, rabbitMQOpsRequest *opsv1alpha1.RabbitMQOpsRequest, opts v1.CreateOptions) (*opsv1alpha1.RabbitMQOpsRequest, error)
	Update(ctx context.Context, rabbitMQOpsRequest *opsv1alpha1.RabbitMQOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.RabbitMQOpsRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rabbitMQOpsRequest *opsv1alpha1.RabbitMQOpsRequest, opts v1.UpdateOptions) (*opsv1alpha1.RabbitMQOpsRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*opsv1alpha1.RabbitMQOpsRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*opsv1alpha1.RabbitMQOpsRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *opsv1alpha1.RabbitMQOpsRequest, err error)
	RabbitMQOpsRequestExpansion
}

// rabbitMQOpsRequests implements RabbitMQOpsRequestInterface
type rabbitMQOpsRequests struct {
	*gentype.ClientWithList[*opsv1alpha1.RabbitMQOpsRequest, *opsv1alpha1.RabbitMQOpsRequestList]
}

// newRabbitMQOpsRequests returns a RabbitMQOpsRequests
func newRabbitMQOpsRequests(c *OpsV1alpha1Client, namespace string) *rabbitMQOpsRequests {
	return &rabbitMQOpsRequests{
		gentype.NewClientWithList[*opsv1alpha1.RabbitMQOpsRequest, *opsv1alpha1.RabbitMQOpsRequestList](
			"rabbitmqopsrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *opsv1alpha1.RabbitMQOpsRequest { return &opsv1alpha1.RabbitMQOpsRequest{} },
			func() *opsv1alpha1.RabbitMQOpsRequestList { return &opsv1alpha1.RabbitMQOpsRequestList{} },
		),
	}
}
