/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	courierv1alpha1 "kubedb.dev/apimachinery/apis/courier/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// BranchLister helps list Branches.
// All objects returned here must be treated as read-only.
type BranchLister interface {
	// List lists all Branches in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*courierv1alpha1.Branch, err error)
	// Branches returns an object that can list and get Branches.
	Branches(namespace string) BranchNamespaceLister
	BranchListerExpansion
}

// branchLister implements the BranchLister interface.
type branchLister struct {
	listers.ResourceIndexer[*courierv1alpha1.Branch]
}

// NewBranchLister returns a new BranchLister.
func NewBranchLister(indexer cache.Indexer) BranchLister {
	return &branchLister{listers.New[*courierv1alpha1.Branch](indexer, courierv1alpha1.Resource("branch"))}
}

// Branches returns an object that can list and get Branches.
func (s *branchLister) Branches(namespace string) BranchNamespaceLister {
	return branchNamespaceLister{listers.NewNamespaced[*courierv1alpha1.Branch](s.ResourceIndexer, namespace)}
}

// BranchNamespaceLister helps list and get Branches.
// All objects returned here must be treated as read-only.
type BranchNamespaceLister interface {
	// List lists all Branches in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*courierv1alpha1.Branch, err error)
	// Get retrieves the Branch from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*courierv1alpha1.Branch, error)
	BranchNamespaceListerExpansion
}

// branchNamespaceLister implements the BranchNamespaceLister
// interface.
type branchNamespaceLister struct {
	listers.ResourceIndexer[*courierv1alpha1.Branch]
}
