/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "kubedb.dev/apimachinery/apis/kubedb/v1"
	kubedbv1 "kubedb.dev/apimachinery/client/clientset/versioned/typed/kubedb/v1"

	gentype "k8s.io/client-go/gentype"
)

// fakePostgreses implements PostgresInterface
type fakePostgreses struct {
	*gentype.FakeClientWithList[*v1.Postgres, *v1.PostgresList]
	Fake *FakeKubedbV1
}

func newFakePostgreses(fake *FakeKubedbV1, namespace string) kubedbv1.PostgresInterface {
	return &fakePostgreses{
		gentype.NewFakeClientWithList[*v1.Postgres, *v1.PostgresList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("postgreses"),
			v1.SchemeGroupVersion.WithKind("Postgres"),
			func() *v1.Postgres { return &v1.Postgres{} },
			func() *v1.PostgresList { return &v1.PostgresList{} },
			func(dst, src *v1.PostgresList) { dst.ListMeta = src.ListMeta },
			func(list *v1.PostgresList) []*v1.Postgres { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.PostgresList, items []*v1.Postgres) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
