/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "kubedb.dev/apimachinery/apis/kubedb/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRedisSentinels implements RedisSentinelInterface
type FakeRedisSentinels struct {
	Fake *FakeKubedbV1
	ns   string
}

var redissentinelsResource = v1.SchemeGroupVersion.WithResource("redissentinels")

var redissentinelsKind = v1.SchemeGroupVersion.WithKind("RedisSentinel")

// Get takes name of the redisSentinel, and returns the corresponding redisSentinel object, and an error if there is any.
func (c *FakeRedisSentinels) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RedisSentinel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(redissentinelsResource, c.ns, name), &v1.RedisSentinel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedisSentinel), err
}

// List takes label and field selectors, and returns the list of RedisSentinels that match those selectors.
func (c *FakeRedisSentinels) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RedisSentinelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(redissentinelsResource, redissentinelsKind, c.ns, opts), &v1.RedisSentinelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RedisSentinelList{ListMeta: obj.(*v1.RedisSentinelList).ListMeta}
	for _, item := range obj.(*v1.RedisSentinelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redisSentinels.
func (c *FakeRedisSentinels) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(redissentinelsResource, c.ns, opts))

}

// Create takes the representation of a redisSentinel and creates it.  Returns the server's representation of the redisSentinel, and an error, if there is any.
func (c *FakeRedisSentinels) Create(ctx context.Context, redisSentinel *v1.RedisSentinel, opts metav1.CreateOptions) (result *v1.RedisSentinel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(redissentinelsResource, c.ns, redisSentinel), &v1.RedisSentinel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedisSentinel), err
}

// Update takes the representation of a redisSentinel and updates it. Returns the server's representation of the redisSentinel, and an error, if there is any.
func (c *FakeRedisSentinels) Update(ctx context.Context, redisSentinel *v1.RedisSentinel, opts metav1.UpdateOptions) (result *v1.RedisSentinel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(redissentinelsResource, c.ns, redisSentinel), &v1.RedisSentinel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedisSentinel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRedisSentinels) UpdateStatus(ctx context.Context, redisSentinel *v1.RedisSentinel, opts metav1.UpdateOptions) (*v1.RedisSentinel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(redissentinelsResource, "status", c.ns, redisSentinel), &v1.RedisSentinel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedisSentinel), err
}

// Delete takes name of the redisSentinel and deletes it. Returns an error if one occurs.
func (c *FakeRedisSentinels) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(redissentinelsResource, c.ns, name, opts), &v1.RedisSentinel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedisSentinels) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(redissentinelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RedisSentinelList{})
	return err
}

// Patch applies the patch and returns the patched redisSentinel.
func (c *FakeRedisSentinels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RedisSentinel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(redissentinelsResource, c.ns, name, pt, data, subresources...), &v1.RedisSentinel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedisSentinel), err
}
