/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisuiv1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"
	versioned "kubedb.dev/apimachinery/client/clientset/versioned"
	internalinterfaces "kubedb.dev/apimachinery/client/informers/externalversions/internalinterfaces"
	uiv1alpha1 "kubedb.dev/apimachinery/client/listers/ui/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SinglestoreInsightInformer provides access to a shared informer and lister for
// SinglestoreInsights.
type SinglestoreInsightInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() uiv1alpha1.SinglestoreInsightLister
}

type singlestoreInsightInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSinglestoreInsightInformer constructs a new informer for SinglestoreInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSinglestoreInsightInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSinglestoreInsightInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSinglestoreInsightInformer constructs a new informer for SinglestoreInsight type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSinglestoreInsightInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().SinglestoreInsights(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().SinglestoreInsights(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().SinglestoreInsights(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.UiV1alpha1().SinglestoreInsights(namespace).Watch(ctx, options)
			},
		},
		&apisuiv1alpha1.SinglestoreInsight{},
		resyncPeriod,
		indexers,
	)
}

func (f *singlestoreInsightInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSinglestoreInsightInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *singlestoreInsightInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisuiv1alpha1.SinglestoreInsight{}, f.defaultInformer)
}

func (f *singlestoreInsightInformer) Lister() uiv1alpha1.SinglestoreInsightLister {
	return uiv1alpha1.NewSinglestoreInsightLister(f.Informer().GetIndexer())
}
