/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNeo4jNodesStatses implements Neo4jNodesStatsInterface
type FakeNeo4jNodesStatses struct {
	Fake *FakeUiV1alpha1
	ns   string
}

var neo4jnodesstatsesResource = v1alpha1.SchemeGroupVersion.WithResource("neo4jnodesstatses")

var neo4jnodesstatsesKind = v1alpha1.SchemeGroupVersion.WithKind("Neo4jNodesStats")

// Get takes name of the neo4jNodesStats, and returns the corresponding neo4jNodesStats object, and an error if there is any.
func (c *FakeNeo4jNodesStatses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Neo4jNodesStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(neo4jnodesstatsesResource, c.ns, name), &v1alpha1.Neo4jNodesStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Neo4jNodesStats), err
}

// List takes label and field selectors, and returns the list of Neo4jNodesStatses that match those selectors.
func (c *FakeNeo4jNodesStatses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.Neo4jNodesStatsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(neo4jnodesstatsesResource, neo4jnodesstatsesKind, c.ns, opts), &v1alpha1.Neo4jNodesStatsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.Neo4jNodesStatsList{ListMeta: obj.(*v1alpha1.Neo4jNodesStatsList).ListMeta}
	for _, item := range obj.(*v1alpha1.Neo4jNodesStatsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested neo4jNodesStatses.
func (c *FakeNeo4jNodesStatses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(neo4jnodesstatsesResource, c.ns, opts))

}

// Create takes the representation of a neo4jNodesStats and creates it.  Returns the server's representation of the neo4jNodesStats, and an error, if there is any.
func (c *FakeNeo4jNodesStatses) Create(ctx context.Context, neo4jNodesStats *v1alpha1.Neo4jNodesStats, opts v1.CreateOptions) (result *v1alpha1.Neo4jNodesStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(neo4jnodesstatsesResource, c.ns, neo4jNodesStats), &v1alpha1.Neo4jNodesStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Neo4jNodesStats), err
}

// Update takes the representation of a neo4jNodesStats and updates it. Returns the server's representation of the neo4jNodesStats, and an error, if there is any.
func (c *FakeNeo4jNodesStatses) Update(ctx context.Context, neo4jNodesStats *v1alpha1.Neo4jNodesStats, opts v1.UpdateOptions) (result *v1alpha1.Neo4jNodesStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(neo4jnodesstatsesResource, c.ns, neo4jNodesStats), &v1alpha1.Neo4jNodesStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Neo4jNodesStats), err
}

// Delete takes name of the neo4jNodesStats and deletes it. Returns an error if one occurs.
func (c *FakeNeo4jNodesStatses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(neo4jnodesstatsesResource, c.ns, name, opts), &v1alpha1.Neo4jNodesStats{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNeo4jNodesStatses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(neo4jnodesstatsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.Neo4jNodesStatsList{})
	return err
}

// Patch applies the patch and returns the patched neo4jNodesStats.
func (c *FakeNeo4jNodesStatses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Neo4jNodesStats, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(neo4jnodesstatsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Neo4jNodesStats{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Neo4jNodesStats), err
}
