/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubedb.dev/apimachinery/apis/ui/v1alpha1"
)

// FakeProxySQLInsights implements ProxySQLInsightInterface
type FakeProxySQLInsights struct {
	Fake *FakeUiV1alpha1
	ns   string
}

var proxysqlinsightsResource = v1alpha1.SchemeGroupVersion.WithResource("proxysqlinsights")

var proxysqlinsightsKind = v1alpha1.SchemeGroupVersion.WithKind("ProxySQLInsight")

// Get takes name of the proxySQLInsight, and returns the corresponding proxySQLInsight object, and an error if there is any.
func (c *FakeProxySQLInsights) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProxySQLInsight, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(proxysqlinsightsResource, c.ns, name), &v1alpha1.ProxySQLInsight{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySQLInsight), err
}

// List takes label and field selectors, and returns the list of ProxySQLInsights that match those selectors.
func (c *FakeProxySQLInsights) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProxySQLInsightList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(proxysqlinsightsResource, proxysqlinsightsKind, c.ns, opts), &v1alpha1.ProxySQLInsightList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProxySQLInsightList{ListMeta: obj.(*v1alpha1.ProxySQLInsightList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProxySQLInsightList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested proxySQLInsights.
func (c *FakeProxySQLInsights) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(proxysqlinsightsResource, c.ns, opts))

}

// Create takes the representation of a proxySQLInsight and creates it.  Returns the server's representation of the proxySQLInsight, and an error, if there is any.
func (c *FakeProxySQLInsights) Create(ctx context.Context, proxySQLInsight *v1alpha1.ProxySQLInsight, opts v1.CreateOptions) (result *v1alpha1.ProxySQLInsight, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(proxysqlinsightsResource, c.ns, proxySQLInsight), &v1alpha1.ProxySQLInsight{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySQLInsight), err
}

// Update takes the representation of a proxySQLInsight and updates it. Returns the server's representation of the proxySQLInsight, and an error, if there is any.
func (c *FakeProxySQLInsights) Update(ctx context.Context, proxySQLInsight *v1alpha1.ProxySQLInsight, opts v1.UpdateOptions) (result *v1alpha1.ProxySQLInsight, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(proxysqlinsightsResource, c.ns, proxySQLInsight), &v1alpha1.ProxySQLInsight{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySQLInsight), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProxySQLInsights) UpdateStatus(ctx context.Context, proxySQLInsight *v1alpha1.ProxySQLInsight, opts v1.UpdateOptions) (*v1alpha1.ProxySQLInsight, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(proxysqlinsightsResource, "status", c.ns, proxySQLInsight), &v1alpha1.ProxySQLInsight{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySQLInsight), err
}

// Delete takes name of the proxySQLInsight and deletes it. Returns an error if one occurs.
func (c *FakeProxySQLInsights) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(proxysqlinsightsResource, c.ns, name, opts), &v1alpha1.ProxySQLInsight{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProxySQLInsights) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(proxysqlinsightsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProxySQLInsightList{})
	return err
}

// Patch applies the patch and returns the patched proxySQLInsight.
func (c *FakeProxySQLInsights) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxySQLInsight, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(proxysqlinsightsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProxySQLInsight{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySQLInsight), err
}
