/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	postgresv1alpha1 "kubedb.dev/apimachinery/apis/postgres/v1alpha1"
	scheme "kubedb.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SubscribersGetter has a method to return a SubscriberInterface.
// A group's client should implement this interface.
type SubscribersGetter interface {
	Subscribers(namespace string) SubscriberInterface
}

// SubscriberInterface has methods to work with Subscriber resources.
type SubscriberInterface interface {
	Create(ctx context.Context, subscriber *postgresv1alpha1.Subscriber, opts v1.CreateOptions) (*postgresv1alpha1.Subscriber, error)
	Update(ctx context.Context, subscriber *postgresv1alpha1.Subscriber, opts v1.UpdateOptions) (*postgresv1alpha1.Subscriber, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, subscriber *postgresv1alpha1.Subscriber, opts v1.UpdateOptions) (*postgresv1alpha1.Subscriber, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*postgresv1alpha1.Subscriber, error)
	List(ctx context.Context, opts v1.ListOptions) (*postgresv1alpha1.SubscriberList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *postgresv1alpha1.Subscriber, err error)
	SubscriberExpansion
}

// subscribers implements SubscriberInterface
type subscribers struct {
	*gentype.ClientWithList[*postgresv1alpha1.Subscriber, *postgresv1alpha1.SubscriberList]
}

// newSubscribers returns a Subscribers
func newSubscribers(c *PostgresV1alpha1Client, namespace string) *subscribers {
	return &subscribers{
		gentype.NewClientWithList[*postgresv1alpha1.Subscriber, *postgresv1alpha1.SubscriberList](
			"subscribers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *postgresv1alpha1.Subscriber { return &postgresv1alpha1.Subscriber{} },
			func() *postgresv1alpha1.SubscriberList { return &postgresv1alpha1.SubscriberList{} },
		),
	}
}
