name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: '1.21'
        id: go

      - uses: actions/checkout@v1

      - name: Run checks
        run: |
          make ci

  kubernetes:
    name: Kubernetes
    runs-on: ubuntu-20.04
    needs: build
    strategy:
      matrix:
        k8s: [v1.19.16, v1.20.15, v1.21.14, v1.22.17, v1.23.17, v1.24.12, v1.25.8, v1.26.3, v1.27.1]
    steps:
      - uses: actions/checkout@v1

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
          image: kindest/node:${{ matrix.k8s }}

      - name: Test crds
        run: |
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          kubectl create -R -f ./crds
