name: Release

on:
  push:
    tags:
      - "*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write  # Grants write access to repository contents, including releases

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Release
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const tag = context.ref.replace('refs/tags/', '');
            await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: tag,
              generate_release_notes: true,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
